# Generated by Django 4.2.7 on 2025-11-10 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin_dashboard', 'Admin Dashboard'), ('system_logs', 'System Logs'), ('user_management', 'User Management'), ('machine_management', 'Machine Management'), ('inventory', 'Inventory Management'), ('quality_control', 'Quality Control Management'), ('system_health', 'System Health'), ('qa_dashboard', 'QA Dashboard'), ('production_manager', 'Production Manager Dashboard'), ('store_dashboard', 'Store Dashboard'), ('qc_dashboard', 'QC Dashboard'), ('regulatory_dashboard', 'Regulatory Dashboard'), ('operator_dashboard', 'Operator Dashboard')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('allowed_roles', models.JSONField(blank=True, default=list, help_text='List of roles that can access this dashboard')),
                ('requires_staff', models.BooleanField(default=False, help_text='Requires is_staff=True')),
                ('requires_superuser', models.BooleanField(default=False, help_text='Requires is_superuser=True')),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('allowed_users', models.ManyToManyField(blank=True, help_text='Specific users who can access this dashboard', to=settings.AUTH_USER_MODEL)),
                ('blocked_users', models.ManyToManyField(blank=True, help_text='Users specifically blocked from this dashboard', related_name='blocked_dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Permission',
                'verbose_name_plural': 'Dashboard Permissions',
                'ordering': ['name'],
            },
        ),
    ]
