# Generated by Django 5.2.8 on 2025-12-04 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_alter_dashboardpermission_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardmetrics',
            options={'ordering': ['-date', 'user__username'], 'verbose_name': 'Dashboard Metric', 'verbose_name_plural': 'Dashboard Metrics'},
        ),
    ]
