# Generated by Django 5.2.8 on 2025-12-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0006_alter_dashboardmetrics_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('qa', 'QA'), ('qc', 'QC'), ('regulatory', 'Regulatory'), ('production_manager', 'Production Manager'), ('store_manager', 'Store Manager'), ('mixing_operator', 'Mixing Operator'), ('granulation_operator', 'Granulation Operator'), ('blending_operator', 'Blending Operator'), ('compression_operator', 'Compression Operator'), ('coating_operator', 'Coating Operator'), ('drying_operator', 'Drying Operator'), ('filling_operator', 'Filling Operator'), ('tube_filling_operator', 'Tube Filling Operator'), ('packing_operator', 'Packing Operator'), ('sorting_operator', 'Sorting Operator'), ('dispensing_operator', 'Dispensing Operator')], max_length=50, unique=True)),
                ('show_notification_panel', models.BooleanField(default=True, help_text='Enable/disable notification panel for this role')),
                ('auto_refresh_notifications', models.BooleanField(default=True, help_text='Auto-refresh notifications without page reload')),
                ('notification_sound', models.BooleanField(default=False, help_text='Play sound when new notification arrives')),
                ('max_notifications_display', models.IntegerField(default=10, help_text='Maximum number of notifications to display in panel')),
            ],
            options={
                'verbose_name': 'Notification Setting',
                'verbose_name_plural': 'Notification Settings',
                'ordering': ['role'],
            },
        ),
    ]
