# Generated by Django 5.2.8 on 2025-12-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0007_notificationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardpermission',
            name='name',
            field=models.CharField(choices=[('admin_dashboard', 'Admin Dashboard'), ('system_logs', 'System Logs'), ('user_management', 'User Management'), ('machine_management', 'Machine Management'), ('inventory', 'Inventory Management'), ('quality_control', 'Quality Control Management'), ('system_health', 'System Health'), ('bmr_reports', 'BMR Print & Download Reports'), ('phase_notifications', 'Phase Timing Alerts'), ('qa_dashboard', 'QA Dashboard'), ('production_manager', 'Production Manager Dashboard'), ('store_dashboard', 'Store Dashboard'), ('qc_dashboard', 'QC Dashboard'), ('regulatory_dashboard', 'Regulatory Dashboard'), ('operator_dashboard', 'Operator Dashboard'), ('pm_notifications', 'Production Manager Notifications'), ('pm_bmr_reports', 'Production Manager BMR Reports'), ('pm_timeline', 'Production Manager Timeline')], max_length=50, unique=True),
        ),
    ]
