# Generated by Django 5.2.8 on 2025-12-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0008_alter_dashboardpermission_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardpermission',
            name='name',
            field=models.CharField(choices=[('admin_dashboard', 'Admin Dashboard'), ('qa_dashboard', 'QA Dashboard'), ('production_manager', 'Production Manager Dashboard'), ('store_dashboard', 'Store Dashboard'), ('qc_dashboard', 'QC Dashboard'), ('regulatory_dashboard', 'Regulatory Dashboard'), ('operator_dashboard', 'Operator Dashboard'), ('analytics', 'Analytics & Metrics'), ('bmr_reports', 'BMR Print & Download Reports'), ('bmr_tracking', 'BMR Tracking'), ('live_tracking', 'Live Production Tracking'), ('machine_management', 'Machine Management'), ('quality_control', 'Quality Control Management'), ('inventory', 'Inventory Management'), ('quarantine', 'Quarantine Tracking'), ('phase_notifications', 'Phase Timing Alerts'), ('user_management', 'User Management'), ('system_health', 'System Health'), ('system_logs', 'System Logs'), ('pm_notifications', 'Production Manager Notifications'), ('pm_bmr_reports', 'Production Manager BMR Reports'), ('pm_timeline', 'Production Manager Timeline')], max_length=50, unique=True),
        ),
    ]
