from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboards', '0014_qms_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='QMSDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('document_type', models.CharField(choices=[('sop', 'SOP'), ('bmr', 'BMR'), ('batch_packing_record', 'Batch Packing Record'), ('master_formula_record', 'Master Formula Record'), ('policy', 'Policy'), ('validation_report', 'Validation Report'), ('other', 'Other Controlled Document')], db_index=True, max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('effective', 'Effective'), ('obsolete', 'Obsolete'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('controlled_file', models.FileField(blank=True, null=True, upload_to='qms_documents/')),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('revision_date', models.DateField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('revision_reason', models.TextField(blank=True)),
                ('revision_history', models.JSONField(blank=True, default=list)),
                ('electronic_signature', models.CharField(blank=True, max_length=180)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_documents_approved', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_documents_owned', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_documents_prepared', to=settings.AUTH_USER_MODEL)),
                ('related_qms_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='dashboards.qmsaction')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_documents_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QMS Document',
                'verbose_name_plural': 'QMS Documents',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='QMSRiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('method', models.CharField(choices=[('fmea', 'FMEA'), ('haccp', 'HACCP'), ('risk_matrix', 'Risk Matrix')], db_index=True, default='fmea', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('mitigation', 'Mitigation'), ('closed', 'Closed')], db_index=True, default='draft', max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('process_area', models.CharField(blank=True, max_length=120)),
                ('hazard', models.TextField(blank=True)),
                ('failure_mode', models.TextField(blank=True)),
                ('cause', models.TextField(blank=True)),
                ('effect', models.TextField(blank=True)),
                ('current_controls', models.TextField(blank=True)),
                ('mitigation_plan', models.TextField(blank=True)),
                ('severity', models.PositiveSmallIntegerField(default=1)),
                ('occurrence', models.PositiveSmallIntegerField(default=1)),
                ('detectability', models.PositiveSmallIntegerField(default=1)),
                ('rpn', models.PositiveIntegerField(default=1)),
                ('residual_severity', models.PositiveSmallIntegerField(default=1)),
                ('residual_occurrence', models.PositiveSmallIntegerField(default=1)),
                ('residual_detectability', models.PositiveSmallIntegerField(default=1)),
                ('residual_rpn', models.PositiveIntegerField(default=1)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_risks_approved', to=settings.AUTH_USER_MODEL)),
                ('bmr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_risks', to='bmr.bmr')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_risks_owned', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_risks', to='products.product')),
                ('qms_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_assessments', to='dashboards.qmsaction')),
            ],
            options={
                'verbose_name': 'QMS Risk Assessment',
                'verbose_name_plural': 'QMS Risk Assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QMSDeviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviation_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('deviation_type', models.CharField(blank=True, max_length=80)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='major', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('impact_assessment', 'Impact Assessment'), ('root_cause', 'Root Cause'), ('capa_required', 'CAPA Required'), ('pending_qa_decision', 'Pending QA Decision'), ('closed', 'Closed')], db_index=True, default='open', max_length=30)),
                ('detection_date', models.DateField(blank=True, null=True)),
                ('immediate_action', models.TextField(blank=True)),
                ('impact_assessment', models.TextField(blank=True)),
                ('root_cause', models.TextField(blank=True)),
                ('qa_decision', models.CharField(blank=True, choices=[('', 'Pending'), ('no_impact', 'No Impact'), ('accept_with_justification', 'Accept With Justification'), ('rework', 'Rework'), ('reject', 'Reject'), ('capa_required', 'CAPA Required')], max_length=40)),
                ('closure_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_deviations_assigned', to=settings.AUTH_USER_MODEL)),
                ('bmr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_deviations', to='bmr.bmr')),
                ('capa_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deviations_as_capa', to='dashboards.qmsaction')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_deviations_closed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_deviations_created', to=settings.AUTH_USER_MODEL)),
                ('defect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_deviations', to='dashboards.qualitydefect')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_deviations', to='products.product')),
                ('qms_action', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deviation_record', to='dashboards.qmsaction')),
                ('quality_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_deviations', to='dashboards.qualityinspectionlot')),
                ('sop_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deviations', to='dashboards.qmsdocument')),
            ],
            options={
                'verbose_name': 'QMS Deviation',
                'verbose_name_plural': 'QMS Deviations',
                'ordering': ['-created_at'],
            },
        ),
    ]
