# Generated by Django 4.2.7 on 2026-07-27 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmr', '0020_delete_historicalbmr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0035_product_capsule_type'),
        ('dashboards', '0017_qmsapprovalroute_qmscalibrationrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QMSQualityQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('query_type', models.CharField(choices=[('customer', 'Customer Query'), ('regulatory', 'Regulatory Query'), ('supplier', 'Supplier Query'), ('internal', 'Internal Query'), ('recall', 'Recall Query'), ('market_complaint', 'Market Complaint Query')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('triage', 'Triage'), ('investigation', 'Investigation'), ('response_draft', 'Response Draft'), ('qa_approved', 'QA Approved'), ('responded', 'Responded'), ('closed', 'Closed')], db_index=True, default='open', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('source', models.CharField(blank=True, max_length=160)),
                ('subject', models.CharField(max_length=180)),
                ('question', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_quality_queries_assigned', to=settings.AUTH_USER_MODEL)),
                ('bmr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_quality_queries', to='bmr.bmr')),
                ('complaint_recall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_queries', to='dashboards.qmscomplaintrecall')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_quality_queries_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_quality_queries', to='products.product')),
                ('qms_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_queries', to='dashboards.qmsaction')),
                ('regulatory_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_queries', to='dashboards.qmsregulatorypackage')),
            ],
            options={
                'verbose_name': 'QMS Quality Query',
                'verbose_name_plural': 'QMS Quality Queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QMSLabInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('event_type', models.CharField(choices=[('oos', 'Out of Specification'), ('oot', 'Out of Trend'), ('atypical', 'Atypical Result'), ('lab_error', 'Laboratory Error'), ('method_deviation', 'Method Deviation')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('phase1_lab_review', 'Phase 1 Lab Review'), ('phase2_full_investigation', 'Phase 2 Full Investigation'), ('qa_review', 'QA Review'), ('capa_required', 'CAPA Required'), ('closed', 'Closed')], db_index=True, default='open', max_length=40)),
                ('disposition', models.CharField(choices=[('pending', 'Pending'), ('valid_result', 'Valid Result'), ('invalid_lab_error', 'Invalid - Lab Error'), ('retest_required', 'Retest Required'), ('batch_reject', 'Batch Reject'), ('batch_release_with_justification', 'Release With Justification')], default='pending', max_length=40)),
                ('test_name', models.CharField(max_length=160)),
                ('specification', models.CharField(blank=True, max_length=255)),
                ('result_value', models.CharField(blank=True, max_length=120)),
                ('trend_reference', models.CharField(blank=True, max_length=160)),
                ('analyst_review', models.TextField(blank=True)),
                ('instrument_review', models.TextField(blank=True)),
                ('method_review', models.TextField(blank=True)),
                ('sample_review', models.TextField(blank=True)),
                ('retest_result', models.CharField(blank=True, max_length=120)),
                ('root_cause', models.TextField(blank=True)),
                ('qa_conclusion', models.TextField(blank=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('bmr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_lab_investigations', to='bmr.bmr')),
                ('capa_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_investigation_capas', to='dashboards.qmsaction')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_lab_investigations_opened', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_lab_investigations', to='products.product')),
                ('qa_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_lab_investigations_reviewed', to=settings.AUTH_USER_MODEL)),
                ('qms_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_investigations', to='dashboards.qmsaction')),
                ('quality_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_investigations', to='dashboards.qualityinspectionlot')),
            ],
            options={
                'verbose_name': 'QMS Lab Investigation',
                'verbose_name_plural': 'QMS Lab Investigations',
                'ordering': ['-opened_at'],
            },
        ),
    ]
