# Generated by Django 4.2.7 on 2026-08-03 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboards', '0019_qmscomment_qmsattachment_qmsactivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='QMSCAPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capa_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('source_type', models.CharField(choices=[('deviation', 'Deviation / OOS'), ('audit', 'Audit Finding'), ('complaint', 'Complaint / Recall'), ('trend', 'Trend / KPI'), ('other', 'Other')], default='other', max_length=20)),
                ('source_reference', models.CharField(blank=True, max_length=180)),
                ('problem_statement', models.TextField(blank=True)),
                ('containment_action', models.TextField(blank=True)),
                ('root_cause_method', models.CharField(blank=True, default='5 Whys', max_length=80)),
                ('root_cause_analysis', models.TextField(blank=True)),
                ('corrective_action_plan', models.TextField(blank=True)),
                ('preventive_action_plan', models.TextField(blank=True)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('effectiveness_method', models.CharField(blank=True, max_length=180)),
                ('effectiveness_criteria', models.TextField(blank=True)),
                ('effectiveness_result', models.CharField(blank=True, choices=[('', 'Not assessed'), ('effective', 'Effective'), ('partially_effective', 'Partially Effective'), ('not_effective', 'Not Effective')], max_length=30)),
                ('effectiveness_evidence', models.TextField(blank=True)),
                ('effectiveness_review_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('investigation', 'Investigation'), ('root_cause_analysis', 'Root Cause Analysis'), ('action_plan', 'Action Plan'), ('implementation', 'Implementation'), ('effectiveness_review', 'Effectiveness Review'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], db_index=True, default='initiated', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('closure_justification', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capa_actions_owned', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capas_approved', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capas_closed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capas_created', to=settings.AUTH_USER_MODEL)),
                ('effectiveness_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capas_effectiveness_verified', to=settings.AUTH_USER_MODEL)),
                ('qa_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capas_reviewed', to=settings.AUTH_USER_MODEL)),
                ('qms_action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capa_record', to='dashboards.qmsaction')),
                ('source_audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capa_records', to='dashboards.qmsaudit')),
                ('source_deviation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capa_records', to='dashboards.qmsdeviation')),
            ],
            options={
                'verbose_name': 'CAPA Record',
                'verbose_name_plural': 'CAPA Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
