# Generated by Django 4.2.7 on 2026-08-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0021_backfill_capa_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationalert',
            name='notification_type',
            field=models.CharField(choices=[('phase_assigned', 'Phase Assigned'), ('phase_completed', 'Phase Completed'), ('phase_rejected', 'Phase Rejected'), ('bmr_approved', 'BMR Approved'), ('quality_alert', 'Quality Alert'), ('deadline_approaching', 'Deadline Approaching'), ('capa_overdue', 'CAPA Overdue'), ('capa_review_due', 'CAPA Review Due'), ('system_maintenance', 'System Maintenance')], max_length=30),
        ),
        migrations.AlterField(
            model_name='qmscapa',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('investigation', 'Investigation'), ('root_cause_analysis', 'Root Cause Analysis'), ('action_plan', 'Action Plan'), ('implementation', 'Implementation'), ('effectiveness_review', 'Effectiveness Review'), ('overdue', 'Overdue'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], db_index=True, default='initiated', max_length=30),
        ),
    ]
