# Generated by Django 4.2.7 on 2026-08-03 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboards', '0022_alter_notificationalert_notification_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QMSChangeControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('change_type', models.CharField(choices=[('process', 'Process'), ('equipment', 'Equipment'), ('facility', 'Facility'), ('material', 'Material'), ('document', 'Document / SOP'), ('system', 'Computerized System')], default='process', max_length=30)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('source_reference', models.CharField(blank=True, max_length=180)),
                ('justification', models.TextField(blank=True)),
                ('current_state', models.TextField(blank=True)),
                ('proposed_state', models.TextField(blank=True)),
                ('quality_impact', models.BooleanField(default=False)),
                ('gmp_impact', models.BooleanField(default=False)),
                ('validation_impact', models.BooleanField(default=False)),
                ('regulatory_impact', models.BooleanField(default=False)),
                ('documentation_impact', models.BooleanField(default=False)),
                ('training_impact', models.BooleanField(default=False)),
                ('stability_impact', models.BooleanField(default=False)),
                ('inventory_impact', models.BooleanField(default=False)),
                ('impact_summary', models.TextField(blank=True)),
                ('qa_impact_decision', models.CharField(blank=True, max_length=180)),
                ('implementation_plan', models.TextField(blank=True)),
                ('implementation_notes', models.TextField(blank=True)),
                ('affected_documents', models.TextField(blank=True)),
                ('training_plan', models.TextField(blank=True)),
                ('validation_plan', models.TextField(blank=True)),
                ('planned_implementation_date', models.DateField(blank=True, null=True)),
                ('actual_implementation_date', models.DateField(blank=True, null=True)),
                ('effectiveness_method', models.CharField(blank=True, max_length=180)),
                ('effectiveness_criteria', models.TextField(blank=True)),
                ('effectiveness_result', models.CharField(blank=True, choices=[('', 'Not assessed'), ('effective', 'Effective'), ('partially_effective', 'Partially Effective'), ('not_effective', 'Not Effective')], max_length=30)),
                ('effectiveness_evidence', models.TextField(blank=True)),
                ('effectiveness_review_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('impact_assessment', 'Impact Assessment'), ('qa_review', 'QA Review'), ('approved', 'Approved'), ('implementation', 'Implementation'), ('effectiveness_review', 'Effectiveness Review'), ('overdue', 'Overdue'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='initiated', max_length=30)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_controls_approved', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_controls_closed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_controls_created', to=settings.AUTH_USER_MODEL)),
                ('effectiveness_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_controls_effectiveness_verified', to=settings.AUTH_USER_MODEL)),
                ('implementation_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_controls_implementation_owned', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_controls_owned', to=settings.AUTH_USER_MODEL)),
                ('qa_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_controls_reviewed', to=settings.AUTH_USER_MODEL)),
                ('qms_action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='change_control_record', to='dashboards.qmsaction')),
            ],
            options={
                'verbose_name': 'Change Control',
                'verbose_name_plural': 'Change Controls',
                'ordering': ['-created_at'],
            },
        ),
    ]
