# Generated by Django 4.2.7 on 2026-08-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0024_backfill_change_controls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationalert',
            name='notification_type',
            field=models.CharField(choices=[('phase_assigned', 'Phase Assigned'), ('phase_completed', 'Phase Completed'), ('phase_rejected', 'Phase Rejected'), ('bmr_approved', 'BMR Approved'), ('quality_alert', 'Quality Alert'), ('deadline_approaching', 'Deadline Approaching'), ('capa_overdue', 'CAPA Overdue'), ('capa_review_due', 'CAPA Review Due'), ('change_control_overdue', 'Change Control Overdue'), ('change_control_due', 'Change Control Due'), ('system_maintenance', 'System Maintenance')], max_length=30),
        ),
        migrations.AlterField(
            model_name='qmsnotificationrule',
            name='trigger_type',
            field=models.CharField(choices=[('document_expiry', 'Document Expiry'), ('capa_overdue', 'CAPA Overdue'), ('change_control_overdue', 'Change Control Overdue'), ('change_control_due', 'Change Control Due'), ('audit_due', 'Audit Due'), ('calibration_due', 'Calibration Due'), ('training_overdue', 'Training Overdue'), ('stability_pull_due', 'Stability Pull Due')], max_length=40),
        ),
    ]
