# Generated by Django 4.2.7 on 2026-08-04 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('dashboards', '0025_alter_notificationalert_notification_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QMSRecordLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_object_id', models.PositiveBigIntegerField()),
                ('to_object_id', models.PositiveBigIntegerField()),
                ('link_type', models.CharField(choices=[('source', 'Source / Origin'), ('caused_by', 'Caused By'), ('addresses', 'Addresses'), ('implements', 'Implements'), ('impacts', 'Impacts'), ('supports', 'Supports'), ('supersedes', 'Supersedes'), ('related', 'Related')], default='related', max_length=30)),
                ('rationale', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_record_links_created', to=settings.AUTH_USER_MODEL)),
                ('from_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qms_links_from', to='contenttypes.contenttype')),
                ('to_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qms_links_to', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='qmsrecordlink',
            constraint=models.UniqueConstraint(fields=('from_content_type', 'from_object_id', 'to_content_type', 'to_object_id', 'link_type'), name='unique_qms_record_link'),
        ),
    ]
