# Generated by Django 4.2.7 on 2026-08-04 05:44

from django.db import migrations


def backfill_links(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    QMSCAPA = apps.get_model('dashboards', 'QMSCAPA')
    QMSChangeControl = apps.get_model('dashboards', 'QMSChangeControl')
    QMSRecordLink = apps.get_model('dashboards', 'QMSRecordLink')

    def link(source, target, link_type, rationale):
        if not source or not target:
            return
        QMSRecordLink.objects.get_or_create(
            from_content_type=ContentType.objects.get_for_model(source, for_concrete_model=False),
            from_object_id=source.pk,
            to_content_type=ContentType.objects.get_for_model(target, for_concrete_model=False),
            to_object_id=target.pk,
            link_type=link_type,
            defaults={'rationale': rationale},
        )

    for capa in QMSCAPA.objects.select_related('source_deviation', 'source_audit'):
        link(capa, capa.source_deviation, 'addresses', 'Existing CAPA source deviation')
        link(capa, capa.source_audit, 'addresses', 'Existing CAPA source audit finding')

    for change in QMSChangeControl.objects.select_related('qms_action'):
        link(change, change.qms_action, 'implements', 'Change Control parent QMS action')


def remove_backfilled_links(apps, schema_editor):
    # Relationships are user-visible traceability records; retain them on rollback.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0026_qms_record_links'),
    ]

    operations = [
        migrations.RunPython(backfill_links, remove_backfilled_links),
    ]
