# Generated by Django 4.2.7 on 2026-08-04 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboards', '0027_backfill_qms_record_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='qmsdocument',
            name='approval_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qmsdocument',
            name='change_control_reference',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='qmsdocument',
            name='document_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qmsdocument',
            name='retention_period_years',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='qmsdocument',
            name='review_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qmsdocument',
            name='supersedes_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='qmsqualityquery',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_quality_queries_closed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qmsqualityquery',
            name='containment_action',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qmsqualityquery',
            name='impact_assessment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qmsqualityquery',
            name='investigation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qmsqualityquery',
            name='qa_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qmsqualityquery',
            name='qa_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_quality_queries_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qmsqualityquery',
            name='qa_review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qmsqualityquery',
            name='resolution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qmsqualityquery',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_quality_queries_responded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qmsqualityquery',
            name='root_cause',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='qmsqualityquery',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('triage', 'Triage'), ('investigation', 'Investigation'), ('response_draft', 'Response Draft'), ('qa_review', 'QA Review'), ('qa_approved', 'QA Approved'), ('responded', 'Responded'), ('closed', 'Closed')], db_index=True, default='open', max_length=30),
        ),
    ]
