# Generated by Django 4.2.7 on 2026-08-04 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboards', '0029_quality_query_collaboration'),
    ]

    operations = [
        migrations.AddField(
            model_name='qmsregulatorypackage',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_regulatory_packages_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qmsregulatorypackage',
            name='authority_reference',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='qmsregulatorypackage',
            name='authority_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qmsregulatorypackage',
            name='authority_response_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qmsregulatorypackage',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qmsregulatorypackage',
            name='commitments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qmsregulatorypackage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='qmsregulatorypackage',
            name='deficiencies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qmsregulatorypackage',
            name='dossier_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qmsregulatorypackage',
            name='internal_approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qmsregulatorypackage',
            name='internal_qa_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qmsregulatorypackage',
            name='outcome_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qmsregulatorypackage',
            name='qa_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_regulatory_packages_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qmsregulatorypackage',
            name='scope_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qmsregulatorypackage',
            name='submission_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='qmsregulatorypackage',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_regulatory_packages_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qmsregulatorypackage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='qmsregulatorypackage',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('compiling', 'Compiling'), ('qa_review', 'QA Review'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('closed', 'Closed')], default='draft', max_length=20),
        ),
    ]
