# Generated by Django 4.2.7 on 2026-08-04 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0030_regulatory_package_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='qmsactivitylog',
            name='qms_regulatory_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='dashboards.qmsregulatorypackage'),
        ),
        migrations.AddField(
            model_name='qmsattachment',
            name='qms_regulatory_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dashboards.qmsregulatorypackage'),
        ),
        migrations.AddField(
            model_name='qmscomment',
            name='qms_regulatory_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dashboards.qmsregulatorypackage'),
        ),
    ]
