# Generated by Django 4.2.7 on 2026-08-04 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboards', '0031_regulatory_package_collaboration'),
    ]

    operations = [
        migrations.AddField(
            model_name='qmstrainingrecord',
            name='assessment_result',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='qmstrainingrecord',
            name='completion_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qmstrainingrecord',
            name='content_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qmstrainingrecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='qmstrainingrecord',
            name='delivery_method',
            field=models.CharField(default='Instructor-led', max_length=80),
        ),
        migrations.AddField(
            model_name='qmstrainingrecord',
            name='effectiveness_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qmstrainingrecord',
            name='effectiveness_result',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qmstrainingrecord',
            name='objective',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qmstrainingrecord',
            name='training_number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='qmstrainingrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='qmstrainingrecord',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qmstrainingrecord',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_training_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qmstrainingrecord',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('awaiting_verification', 'Awaiting Verification'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('failed', 'Failed'), ('waived', 'Waived')], default='assigned', max_length=30),
        ),
    ]
