# Generated by Django 4.2.7 on 2026-08-04 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboards', '0033_training_collaboration'),
    ]

    operations = [
        migrations.AddField(
            model_name='qmsactivitylog',
            name='qms_calibration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='dashboards.qmscalibrationrecord'),
        ),
        migrations.AddField(
            model_name='qmsattachment',
            name='qms_calibration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dashboards.qmscalibrationrecord'),
        ),
        migrations.AddField(
            model_name='qmscalibrationrecord',
            name='acceptance_criteria',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qmscalibrationrecord',
            name='calibration_interval_days',
            field=models.PositiveIntegerField(default=365),
        ),
        migrations.AddField(
            model_name='qmscalibrationrecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='qmscalibrationrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_calibration_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qmscalibrationrecord',
            name='location',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='qmscalibrationrecord',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='qmscalibrationrecord',
            name='method_reference',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='qmscalibrationrecord',
            name='model_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='qmscalibrationrecord',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_calibration_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qmscalibrationrecord',
            name='serial_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='qmscalibrationrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='qmscalibrationrecord',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qmscalibrationrecord',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_calibration_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qmscomment',
            name='qms_calibration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dashboards.qmscalibrationrecord'),
        ),
        migrations.CreateModel(
            name='QMSCalibrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibration_date', models.DateField()),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('conditional', 'Conditional')], default='pass', max_length=20)),
                ('certificate_number', models.CharField(blank=True, max_length=120)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='qms_calibration/events/')),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('calibration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dashboards.qmscalibrationrecord')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_calibration_events_performed', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_calibration_events_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-calibration_date', '-created_at'],
            },
        ),
    ]
