# Generated by Django 4.2.7 on 2026-08-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0034_qmsactivitylog_qms_calibration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationalert',
            name='notification_type',
            field=models.CharField(choices=[('phase_assigned', 'Phase Assigned'), ('phase_completed', 'Phase Completed'), ('phase_rejected', 'Phase Rejected'), ('bmr_approved', 'BMR Approved'), ('quality_alert', 'Quality Alert'), ('deadline_approaching', 'Deadline Approaching'), ('capa_overdue', 'CAPA Overdue'), ('capa_review_due', 'CAPA Review Due'), ('change_control_overdue', 'Change Control Overdue'), ('change_control_due', 'Change Control Due'), ('calibration_overdue', 'Calibration Overdue'), ('calibration_due', 'Calibration Due'), ('system_maintenance', 'System Maintenance')], max_length=30),
        ),
    ]
