# Generated by Django 4.2.7 on 2026-08-04 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bmr', '0020_delete_historicalbmr'),
        ('products', '0035_product_capsule_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboards', '0035_alter_notificationalert_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='qmsactivitylog',
            name='qms_stability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='dashboards.qmsstabilityschedule'),
        ),
        migrations.AddField(
            model_name='qmsactivitylog',
            name='qms_supplier_quality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='dashboards.qmssupplierqualification'),
        ),
        migrations.AddField(
            model_name='qmsattachment',
            name='qms_stability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dashboards.qmsstabilityschedule'),
        ),
        migrations.AddField(
            model_name='qmsattachment',
            name='qms_supplier_quality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dashboards.qmssupplierqualification'),
        ),
        migrations.AddField(
            model_name='qmscomment',
            name='qms_stability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dashboards.qmsstabilityschedule'),
        ),
        migrations.AddField(
            model_name='qmscomment',
            name='qms_supplier_quality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dashboards.qmssupplierqualification'),
        ),
        migrations.AddField(
            model_name='qmsstabilityschedule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='qmsstabilityschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_stability_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qmsstabilityschedule',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_stability_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qmsstabilityschedule',
            name='protocol_reference',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='qmsstabilityschedule',
            name='qa_review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qmsstabilityschedule',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qmsstabilityschedule',
            name='specification_reference',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='qmsstabilityschedule',
            name='storage_condition',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='qmsstabilityschedule',
            name='study_number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='qmsstabilityschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='qmssupplierqualification',
            name='contact_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qmssupplierqualification',
            name='material_specification',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='qmssupplierqualification',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_supplier_quality_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qmssupplierqualification',
            name='quality_agreement_reference',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='qmssupplierqualification',
            name='supplier_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='qmsstabilityschedule',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('pulled', 'Pulled'), ('tested', 'Tested'), ('reviewed', 'Reviewed'), ('qa_review', 'QA Review'), ('failed', 'Failed / Investigation'), ('closed', 'Closed')], default='scheduled', max_length=20),
        ),
        migrations.CreateModel(
            name='QMSStabilityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=160)),
                ('result_value', models.CharField(blank=True, max_length=120)),
                ('specification', models.CharField(blank=True, max_length=255)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('test_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_stability_results', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='dashboards.qmsstabilityschedule')),
            ],
            options={
                'ordering': ['test_date', 'test_name'],
            },
        ),
        migrations.CreateModel(
            name='QMSMaterialQC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_lot_number', models.CharField(max_length=100, unique=True)),
                ('material_name', models.CharField(max_length=180)),
                ('material_code', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('received', 'Received'), ('sampling', 'Sampling'), ('testing', 'Testing'), ('qa_review', 'QA Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('on_hold', 'On Hold')], db_index=True, default='received', max_length=20)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('supplier_certificate_file', models.FileField(blank=True, null=True, upload_to='qms_material_qc/')),
                ('result_summary', models.TextField(blank=True)),
                ('qa_decision_notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_material_qc_approved', to=settings.AUTH_USER_MODEL)),
                ('bmr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_qc_records', to='bmr.bmr')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_material_qc_owned', to=settings.AUTH_USER_MODEL)),
                ('qa_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_material_qc_reviewed', to=settings.AUTH_USER_MODEL)),
                ('sampling_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_qc_records', to='dashboards.qmssamplingplan')),
                ('specification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_qc_records', to='dashboards.qmslabspecification')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_qc_records', to='dashboards.qmssupplierqualification')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QMSCOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coa_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('qc_prepared', 'Prepared by QC'), ('qa_review', 'QA Review'), ('approved', 'Approved / Released'), ('rejected', 'Rejected'), ('void', 'Void')], db_index=True, default='draft', max_length=20)),
                ('market', models.CharField(blank=True, max_length=120)),
                ('specification_reference', models.CharField(blank=True, max_length=160)),
                ('result_summary', models.TextField(blank=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='qms_coa/')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_coas_approved', to=settings.AUTH_USER_MODEL)),
                ('bmr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_coas', to='bmr.bmr')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_coas_prepared', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_coas', to='products.product')),
                ('qa_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_coas_reviewed', to=settings.AUTH_USER_MODEL)),
                ('quality_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_coas', to='dashboards.qualityinspectionlot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='qmsactivitylog',
            name='qms_coa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='dashboards.qmscoa'),
        ),
        migrations.AddField(
            model_name='qmsactivitylog',
            name='qms_material_qc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='dashboards.qmsmaterialqc'),
        ),
        migrations.AddField(
            model_name='qmsattachment',
            name='qms_coa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dashboards.qmscoa'),
        ),
        migrations.AddField(
            model_name='qmsattachment',
            name='qms_material_qc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dashboards.qmsmaterialqc'),
        ),
        migrations.AddField(
            model_name='qmscomment',
            name='qms_coa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dashboards.qmscoa'),
        ),
        migrations.AddField(
            model_name='qmscomment',
            name='qms_material_qc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dashboards.qmsmaterialqc'),
        ),
    ]
