# Generated by Django 4.2.7 on 2026-06-02 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axes_enabled', models.BooleanField(default=True, help_text='Lock accounts after multiple failed login attempts', verbose_name='Enable Brute Force Protection')),
                ('axes_failure_limit', models.IntegerField(default=5, help_text='Number of failed attempts before account lockout (e.g., 3, 5, 10)', verbose_name='Failed Login Attempts Limit')),
                ('axes_cooloff_hours', models.DecimalField(decimal_places=2, default=1.0, help_text='How long to lock account (e.g., 0.25 = 15 min, 0.5 = 30 min, 1 = 1 hour)', max_digits=5, verbose_name='Lockout Duration (Hours)')),
                ('password_min_length', models.IntegerField(default=12, help_text='Minimum characters required for passwords', verbose_name='Minimum Password Length')),
                ('session_timeout_hours', models.IntegerField(default=12, help_text='Auto-logout users after this many hours of inactivity', verbose_name='Session Timeout (Hours)')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Configuration',
                'verbose_name_plural': 'Security Configuration',
                'db_table': 'security_settings',
            },
        ),
    ]
