# Generated by Django 4.2.7 on 2026-07-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_securitysettings_session_timeout_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitysettings',
            name='session_timeout_hours',
        ),
    ]
