# Generated by Django 5.2.6 on 2025-10-11 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bmr', '0004_bmrrequest'),
        ('workflow', '0009_batchphaseexecution_breakdown_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarantineBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('quarantined', 'In Quarantine'), ('sample_requested', 'Sample Requested'), ('sample_in_qa', 'Sample with QA'), ('sample_in_qc', 'Sample with QC'), ('sample_approved', 'Sample Approved'), ('sample_failed', 'Sample Failed'), ('released', 'Released to Next Phase')], default='quarantined', max_length=20)),
                ('quarantine_date', models.DateTimeField(auto_now_add=True)),
                ('released_date', models.DateTimeField(blank=True, null=True)),
                ('sample_count', models.PositiveSmallIntegerField(default=0)),
                ('bmr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantine_batches', to='bmr.bmr')),
                ('current_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.productionphase')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_quarantine_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-quarantine_date'],
                'unique_together': {('bmr', 'current_phase')},
            },
        ),
        migrations.CreateModel(
            name='SampleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_number', models.PositiveSmallIntegerField()),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('sample_date', models.DateTimeField(blank=True, null=True)),
                ('qa_comments', models.TextField(blank=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('qc_status', models.CharField(choices=[('pending', 'Pending QC Review'), ('approved', 'Approved'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('qc_comments', models.TextField(blank=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_samples', to=settings.AUTH_USER_MODEL)),
                ('quarantine_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_requests', to='quarantine.quarantinebatch')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_samples', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_samples', to=settings.AUTH_USER_MODEL)),
                ('sampled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sampled_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-request_date'],
                'unique_together': {('quarantine_batch', 'sample_number')},
            },
        ),
    ]
