# Generated by Django 5.2.6 on 2025-10-11 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quarantine', '0001_initial'),
    ]

    operations = [
    ]
