# Generated by Django 4.2.7 on 2025-09-30 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_batchphaseexecution_breakdown_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchphaseexecution',
            name='rework_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batchphaseexecution',
            name='rollback_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reworked_to', to='workflow.batchphaseexecution'),
        ),
        migrations.AddField(
            model_name='batchphaseexecution',
            name='rollback_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
