# Generated by Django 4.2.7 on 2025-10-16 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_batchphaseexecution_rework_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchphaseexecution',
            name='rework_count',
        ),
        migrations.RemoveField(
            model_name='batchphaseexecution',
            name='rollback_from',
        ),
        migrations.RemoveField(
            model_name='batchphaseexecution',
            name='rollback_reason',
        ),
    ]
