# Generated by Django 4.2.7 on 2025-10-23 09:38

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bmr', '0005_bmr_manufacturing_date'),
        ('workflow', '0011_remove_batchphaseexecution_rework_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseOverrunNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expected_duration', models.DecimalField(decimal_places=2, help_text='Expected duration in hours', max_digits=5)),
                ('actual_duration', models.DecimalField(decimal_places=2, help_text='Actual duration in hours', max_digits=5)),
                ('operator_response', models.TextField(blank=True)),
                ('response_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Response'), ('responded', 'Operator Responded'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('admin_comments', models.TextField(blank=True)),
                ('admin_review_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Phase Overrun Notification',
                'verbose_name_plural': 'Phase Overrun Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhaseTimingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_duration_hours', models.DecimalField(decimal_places=2, help_text='Expected duration in hours', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('warning_threshold_percent', models.PositiveIntegerField(default=20, help_text='Percentage over expected duration before warning (e.g. 20 for 20%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_timings_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phase Timing Setting',
                'verbose_name_plural': 'Phase Timing Settings',
                'ordering': ['phase__phase_name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='phaseoperator',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='phaseoperator',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='phaseoperator',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='batchphaseexecution',
            options={'ordering': ['bmr', 'phase__phase_order'], 'verbose_name': 'Batch Phase Execution', 'verbose_name_plural': 'Batch Phase Executions'},
        ),
        migrations.AlterModelOptions(
            name='productionphase',
            options={'ordering': ['product_type', 'phase_order'], 'verbose_name': 'Production Phase', 'verbose_name_plural': 'Production Phases'},
        ),
        migrations.AlterUniqueTogether(
            name='batchphaseexecution',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='machine',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='productionphase',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productionphase',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productionphase',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='batchphaseexecution',
            name='bmr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmr.bmr'),
        ),
        migrations.AlterField(
            model_name='batchphaseexecution',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phases_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='batchphaseexecution',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.productionphase'),
        ),
        migrations.AlterField(
            model_name='batchphaseexecution',
            name='qc_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qc_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='batchphaseexecution',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phases_started', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='batchphaseexecution',
            name='started_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 23, 9, 38, 39, 910563, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batchphaseexecution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='machine',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productionphase',
            name='phase_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productionphase',
            name='product_type',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='PhaseCheckpoint',
        ),
        migrations.DeleteModel(
            name='PhaseOperator',
        ),
        migrations.AddField(
            model_name='phasetimingsetting',
            name='phase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timing_setting', to='workflow.productionphase'),
        ),
        migrations.AddField(
            model_name='phaseoverrunnotification',
            name='batch_phase_execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timing_notifications', to='workflow.batchphaseexecution'),
        ),
        migrations.AddField(
            model_name='phaseoverrunnotification',
            name='timing_setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrun_notifications', to='workflow.phasetimingsetting'),
        ),
        migrations.RemoveField(
            model_name='batchphaseexecution',
            name='breakdown_reason',
        ),
        migrations.RemoveField(
            model_name='batchphaseexecution',
            name='changeover_reason',
        ),
        migrations.RemoveField(
            model_name='batchphaseexecution',
            name='phase_data',
        ),
        migrations.RemoveField(
            model_name='productionphase',
            name='can_rollback_to',
        ),
        migrations.RemoveField(
            model_name='productionphase',
            name='estimated_duration_hours',
        ),
    ]
