# Generated by Django 4.2.7 on 2025-10-23 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0012_phaseoverrunnotification_phasetimingsetting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseTimeOverrunNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_response', models.TextField(blank=True)),
                ('notification_date', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledgment_date', models.DateTimeField(blank=True, null=True)),
                ('notified_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_overrun_notifications', to=settings.AUTH_USER_MODEL)),
                ('phase_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.batchphaseexecution')),
            ],
            options={
                'ordering': ['-notification_date'],
            },
        ),
    ]
