# Generated by Django 4.2.7 on 2025-10-24 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmr', '0005_bmr_manufacturing_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0014_alter_productionphase_phase_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint_name', models.CharField(max_length=200)),
                ('expected_value', models.CharField(max_length=200)),
                ('actual_value', models.CharField(blank=True, max_length=200)),
                ('is_within_spec', models.BooleanField(blank=True, null=True)),
                ('checked_date', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhaseOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary_operator', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='phasetimeoverrunnotification',
            name='notified_admin',
        ),
        migrations.RemoveField(
            model_name='phasetimeoverrunnotification',
            name='phase_execution',
        ),
        migrations.RemoveField(
            model_name='phasetimingsetting',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='phasetimingsetting',
            name='phase',
        ),
        migrations.AlterModelOptions(
            name='batchphaseexecution',
            options={'ordering': ['bmr', 'phase__phase_order']},
        ),
        migrations.AlterModelOptions(
            name='productionphase',
            options={'ordering': ['product_type', 'phase_order']},
        ),
        migrations.AddField(
            model_name='batchphaseexecution',
            name='breakdown_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='batchphaseexecution',
            name='changeover_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='batchphaseexecution',
            name='phase_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='productionphase',
            name='can_rollback_to',
            field=models.ForeignKey(blank=True, help_text='Phase to rollback to if this phase fails', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.productionphase'),
        ),
        migrations.AddField(
            model_name='productionphase',
            name='estimated_duration_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='batchphaseexecution',
            name='bmr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_executions', to='bmr.bmr'),
        ),
        migrations.AlterField(
            model_name='batchphaseexecution',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_phases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='batchphaseexecution',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.productionphase'),
        ),
        migrations.AlterField(
            model_name='batchphaseexecution',
            name='qc_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_approved_phases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='batchphaseexecution',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_phases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='batchphaseexecution',
            name='started_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batchphaseexecution',
            name='status',
            field=models.CharField(choices=[('not_ready', 'Not Ready'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('rolled_back', 'Rolled Back')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='machine',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Active machines are available for selection'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(choices=[('granulation', 'Granulation'), ('blending', 'Blending'), ('compression', 'Compression'), ('coating', 'Coating'), ('blister_packing', 'Blister Packing'), ('filling', 'Filling')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productionphase',
            name='phase_name',
            field=models.CharField(choices=[('bmr_creation', 'BMR Creation'), ('regulatory_approval', 'Regulatory Approval'), ('material_dispensing', 'Material Dispensing'), ('quality_control', 'Quality Control'), ('post_compression_qc', 'Post-Compression QC'), ('post_mixing_qc', 'Post-Mixing QC'), ('post_blending_qc', 'Post-Blending QC'), ('packaging_material_release', 'Packaging Material Release'), ('secondary_packaging', 'Secondary Packaging'), ('final_qa', 'Final QA'), ('finished_goods_store', 'Finished Goods Store'), ('mixing', 'Mixing'), ('tube_filling', 'Tube Filling'), ('granulation', 'Granulation'), ('blending', 'Blending'), ('compression', 'Compression'), ('sorting', 'Sorting'), ('coating', 'Coating'), ('blister_packing', 'Blister Packing'), ('bulk_packing', 'Bulk Packing'), ('drying', 'Drying'), ('filling', 'Filling')], max_length=30),
        ),
        migrations.AlterField(
            model_name='productionphase',
            name='product_type',
            field=models.CharField(choices=[('ointment', 'Ointment'), ('tablet_normal', 'Tablet Normal'), ('tablet_2', 'Tablet 2'), ('capsule', 'Capsule')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='batchphaseexecution',
            unique_together={('bmr', 'phase')},
        ),
        migrations.AlterUniqueTogether(
            name='machine',
            unique_together={('name', 'machine_type')},
        ),
        migrations.AlterUniqueTogether(
            name='productionphase',
            unique_together={('product_type', 'phase_name')},
        ),
        migrations.DeleteModel(
            name='PhaseOverrunNotification',
        ),
        migrations.DeleteModel(
            name='PhaseTimeOverrunNotification',
        ),
        migrations.DeleteModel(
            name='PhaseTimingSetting',
        ),
        migrations.AddField(
            model_name='phaseoperator',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.productionphase'),
        ),
        migrations.AddField(
            model_name='phaseoperator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phasecheckpoint',
            name='phase_execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='workflow.batchphaseexecution'),
        ),
        migrations.RemoveField(
            model_name='productionphase',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='productionphase',
            name='description',
        ),
        migrations.AlterUniqueTogether(
            name='phaseoperator',
            unique_together={('user', 'phase')},
        ),
    ]
