# Generated by Django 4.2.7 on 2025-10-24 09:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0015_add_phase_data_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseTimingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_duration_hours', models.DecimalField(decimal_places=2, help_text='Expected duration in hours', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('warning_threshold_percent', models.PositiveIntegerField(default=20, help_text='Percentage over expected duration before warning (e.g. 20 for 20%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_timings_created', to=settings.AUTH_USER_MODEL)),
                ('phase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timing_setting', to='workflow.productionphase')),
            ],
            options={
                'verbose_name': 'Phase Timing Setting',
                'verbose_name_plural': 'Phase Timing Settings',
                'ordering': ['phase__phase_name'],
            },
        ),
        migrations.CreateModel(
            name='PhaseTimeOverrunNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_time', models.DateTimeField(auto_now_add=True)),
                ('threshold_exceeded_percent', models.PositiveIntegerField()),
                ('message', models.TextField()),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_overrun_notifications', to=settings.AUTH_USER_MODEL)),
                ('notified_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_overrun_notifications', to=settings.AUTH_USER_MODEL)),
                ('phase_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_overrun_notifications', to='workflow.batchphaseexecution')),
            ],
            options={
                'verbose_name': 'Phase Time Overrun Notification',
                'verbose_name_plural': 'Phase Time Overrun Notifications',
                'ordering': ['-notification_time'],
            },
        ),
        migrations.CreateModel(
            name='PhaseOverrunNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expected_duration', models.DecimalField(decimal_places=2, help_text='Expected duration in hours', max_digits=5)),
                ('actual_duration', models.DecimalField(decimal_places=2, help_text='Actual duration in hours', max_digits=5)),
                ('operator_response', models.TextField(blank=True)),
                ('response_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Response'), ('responded', 'Operator Responded'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('admin_comments', models.TextField(blank=True)),
                ('admin_review_time', models.DateTimeField(blank=True, null=True)),
                ('phase_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrun_notifications', to='workflow.batchphaseexecution')),
            ],
            options={
                'verbose_name': 'Phase Overrun Notification',
                'verbose_name_plural': 'Phase Overrun Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
