# Generated by Django 4.2.7 on 2025-11-11 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0016_restore_timing_notification_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name (e.g., 'Standard Tablet Workflow')", max_length=100)),
                ('product_type', models.CharField(choices=[('ointment', 'Ointment'), ('tablet', 'Tablet'), ('capsule', 'Capsule')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of when to use this template')),
                ('is_active', models.BooleanField(default=True, help_text='Active templates are available for new BMRs')),
                ('is_default', models.BooleanField(default=False, help_text='Default template for this product type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['product_type', 'name'],
                'unique_together': {('product_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplatePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_name', models.CharField(max_length=50)),
                ('phase_order', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('estimated_duration_hours', models.DecimalField(decimal_places=2, default=4.0, max_digits=5)),
                ('rollback_target_order', models.PositiveIntegerField(blank=True, help_text='Phase order to rollback to if this phase fails (must be lower number)', null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='workflow.workflowtemplate')),
            ],
            options={
                'ordering': ['template', 'phase_order'],
                'unique_together': {('template', 'phase_name'), ('template', 'phase_order')},
            },
        ),
    ]
