# Generated by Django 4.2.7 on 2025-11-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0017_workflowtemplate_workflowtemplatephase'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionphase',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this phase'),
        ),
        migrations.AlterField(
            model_name='productionphase',
            name='product_type',
            field=models.CharField(choices=[('ointment', 'Ointment'), ('tablet', 'Tablet'), ('capsule', 'Capsule')], max_length=20),
        ),
    ]
