# Generated by Django 4.2.7 on 2025-11-12 09:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0006_remove_product_maximum_batch_size_and_more'),
        ('workflow', '0018_productionphase_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMachineTimingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_duration_hours', models.DecimalField(decimal_places=2, help_text='Expected duration for this product-machine-phase combination', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('warning_threshold_percent', models.PositiveIntegerField(default=20, help_text='Percentage over expected duration before warning (e.g. 20 for 20%)')),
                ('is_active', models.BooleanField(default=True, help_text='Active timing settings')),
                ('notes', models.TextField(blank=True, help_text="Notes about this timing setting (e.g., 'Machine A is slower for heavy products')")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_machine_timings_created', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(blank=True, help_text='Leave blank for non-machine phases', null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.machine')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.productionphase')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Product-Machine Timing Setting',
                'verbose_name_plural': 'Product-Machine Timing Settings',
                'ordering': ['product__product_name', 'phase__phase_name', 'machine__name'],
                'unique_together': {('product', 'machine', 'phase')},
            },
        ),
    ]
