# Generated by Django 4.2.7 on 2025-11-18 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0019_fix_production_phase_ordering'),
        ('workflow', '0019_productmachinetimingsetting'),
    ]

    operations = [
    ]
