# Generated by Django 4.2.7 on 2025-11-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0020_merge_20251118_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemTimingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(help_text='Unique identifier for this timing setting', max_length=100, unique=True)),
                ('setting_value', models.DecimalField(decimal_places=2, help_text='Numeric value for this setting', max_digits=8)),
                ('description', models.TextField(help_text='Description of what this setting controls')),
                ('unit', models.CharField(default='hours', help_text='Unit of measurement (hours, minutes, percentage, etc.)', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Timing Setting',
                'verbose_name_plural': 'System Timing Settings',
                'ordering': ['setting_name'],
            },
        ),
    ]
