# Generated by Django 4.2.7 on 2025-11-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0021_systemtimingsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('setting_value', models.TextField()),
                ('data_type', models.CharField(choices=[('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('string', 'String'), ('json', 'JSON')], default='string', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('dashboard_ui', 'Dashboard UI'), ('refresh_timing', 'Refresh Timing'), ('pagination', 'Pagination'), ('user_preferences', 'User Preferences'), ('mobile_responsive', 'Mobile Responsive')], default='dashboard_ui', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_restart', models.BooleanField(default=False, help_text='Whether changing this setting requires server restart')),
                ('last_modified_by', models.CharField(blank=True, max_length=150)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Setting',
                'verbose_name_plural': 'Dashboard Settings',
                'ordering': ['category', 'setting_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionLimitsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('setting_value', models.TextField()),
                ('data_type', models.CharField(choices=[('integer', 'Integer'), ('float', 'Float'), ('string', 'String')], default='integer', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(choices=[('batch_limits', 'Batch Limits'), ('pagination_limits', 'Pagination Limits'), ('file_limits', 'File Upload Limits'), ('concurrent_operations', 'Concurrent Operations'), ('resource_limits', 'Resource Limits')], default='batch_limits', max_length=50)),
                ('min_value', models.FloatField(blank=True, help_text='Minimum allowed value', null=True)),
                ('max_value', models.FloatField(blank=True, help_text='Maximum allowed value', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_restart', models.BooleanField(default=False)),
                ('last_modified_by', models.CharField(blank=True, max_length=150)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Production Limit Setting',
                'verbose_name_plural': 'Production Limit Settings',
                'ordering': ['category', 'setting_name'],
            },
        ),
        migrations.CreateModel(
            name='SessionManagementSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('setting_value', models.TextField()),
                ('data_type', models.CharField(choices=[('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('string', 'String')], default='string', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(choices=[('session_timeout', 'Session Timeout'), ('authentication', 'Authentication'), ('password_policy', 'Password Policy'), ('two_factor_auth', 'Two Factor Authentication'), ('security_logging', 'Security Logging')], default='session_timeout', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_restart', models.BooleanField(default=False)),
                ('last_modified_by', models.CharField(blank=True, max_length=150)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Session Management Setting',
                'verbose_name_plural': 'Session Management Settings',
                'ordering': ['category', 'setting_name'],
            },
        ),
        migrations.CreateModel(
            name='SystemAlertSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('setting_value', models.TextField()),
                ('data_type', models.CharField(choices=[('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('string', 'String'), ('email_list', 'Email List')], default='string', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('email_alerts', 'Email Alerts'), ('sms_alerts', 'SMS Alerts'), ('dashboard_notifications', 'Dashboard Notifications'), ('overrun_alerts', 'Phase Overrun Alerts'), ('quality_alerts', 'Quality Alerts'), ('system_maintenance', 'System Maintenance')], default='dashboard_notifications', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_modified_by', models.CharField(blank=True, max_length=150)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Alert Setting',
                'verbose_name_plural': 'System Alert Settings',
                'ordering': ['category', 'setting_name'],
            },
        ),
    ]
