# Generated by Django 5.2.8 on 2025-11-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0022_create_admin_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='phases',
            field=models.ManyToManyField(blank=True, help_text='Select all production phases this machine can perform.', related_name='machines', to='workflow.productionphase'),
        ),
    ]
