# Generated by Django 5.2.8 on 2025-11-26 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0024_producttypeconfiguration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttypeconfiguration',
            options={'ordering': ['product_type_key'], 'verbose_name': 'Product Type Configuration', 'verbose_name_plural': 'Product Type Configurations'},
        ),
        migrations.RemoveField(
            model_name='machine',
            name='phases',
        ),
        migrations.AlterField(
            model_name='batchphaseexecution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('not_ready', 'Not Ready')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='producttypeconfiguration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_product_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producttypeconfiguration',
            name='default_packing_phase',
            field=models.CharField(blank=True, help_text="Default packing phase for this product (e.g., 'blister_packing', 'bulk_packing', 'tube_filling')", max_length=50),
        ),
        migrations.AlterField(
            model_name='producttypeconfiguration',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this product type and its production characteristics'),
        ),
        migrations.AlterField(
            model_name='producttypeconfiguration',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Inactive product types won't be available for new BMRs"),
        ),
        migrations.AlterField(
            model_name='producttypeconfiguration',
            name='product_type_display',
            field=models.CharField(help_text="Display name for this product type (e.g., 'Tablet Type 3')", max_length=100),
        ),
    ]
