"""Add behavior_tags to ProductTypeConfiguration and backfill common tags

Generated by assistant: adds JSONField `behavior_tags` and backfills base types.
"""
from django.db import migrations, models


def backfill_behavior_tags(apps, schema_editor):
    ProductTypeConfiguration = apps.get_model('workflow', 'ProductTypeConfiguration')
    # Common tags mapping for seeded product types
    mapping = {
        'tablet': ['tablet-like', 'may_coat'],
        'capsule': ['capsule-like'],
        'ointment': ['ointment-like']
    }

    for key, tags in mapping.items():
        try:
            obj = ProductTypeConfiguration.objects.filter(product_type_key__iexact=key).first()
            if obj:
                # Only set if empty
                existing = getattr(obj, 'behavior_tags', None)
                if not existing:
                    obj.behavior_tags = tags
                    obj.save()
        except Exception:
            continue


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0025_alter_producttypeconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttypeconfiguration',
            name='behavior_tags',
            field=models.JSONField(default=list, blank=True, help_text="Flexible tags describing product behavior (JSON list). Use admin checkboxes for common tags."),
        ),
        migrations.RunPython(backfill_behavior_tags, reverse_code=migrations.RunPython.noop),
    ]
