# Generated by Django 5.2.8 on 2025-12-01 10:42

import workflow.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0026_add_producttype_behavior_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionphase',
            name='phase_name',
            field=models.CharField(choices=workflow.constants.get_phase_choices, max_length=30),
        ),
        migrations.AlterField(
            model_name='productionphase',
            name='product_type',
            field=models.CharField(choices=workflow.constants.get_product_type_choices, max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='product_type',
            field=models.CharField(choices=workflow.constants.get_product_type_choices, max_length=20),
        ),
    ]
