# Generated by Django 5.2.8 on 2025-12-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0027_alter_productionphase_phase_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionphase',
            name='phase_name',
            field=models.CharField(choices=[('bmr_creation', 'BMR Creation'), ('regulatory_approval', 'Regulatory Approval'), ('material_dispensing', 'Material Dispensing'), ('quality_control', 'Quality Control'), ('post_compression_qc', 'Post-Compression QC'), ('post_mixing_qc', 'Post-Mixing QC'), ('post_blending_qc', 'Post-Blending QC'), ('packaging_material_release', 'Packaging Material Release'), ('secondary_packaging', 'Secondary Packaging'), ('final_qa', 'Final QA'), ('finished_goods_store', 'Finished Goods Store'), ('mixing', 'Mixing'), ('tube_filling', 'Tube Filling'), ('granulation', 'Granulation'), ('blending', 'Blending'), ('compression', 'Compression'), ('sorting', 'Sorting'), ('coating', 'Coating'), ('blister_packing', 'Blister Packing'), ('bulk_packing', 'Bulk Packing'), ('drying', 'Drying'), ('filling', 'Filling')], max_length=30),
        ),
        migrations.AlterField(
            model_name='productionphase',
            name='product_type',
            field=models.CharField(choices=[('ointment', 'Ointment'), ('tablet', 'Tablet'), ('capsule', 'Capsule')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='product_type',
            field=models.CharField(choices=[('ointment', 'Ointment'), ('tablet', 'Tablet'), ('capsule', 'Capsule')], max_length=20),
        ),
    ]
