# Generated by Django 5.2.8 on 2025-12-02 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0028_alter_productionphase_phase_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionphase',
            name='qa_can_rollback_to',
            field=models.ForeignKey(blank=True, help_text='Phase to rollback to if QA/Final QA fails this phase', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_rollback_from', to='workflow.productionphase'),
        ),
        migrations.AddField(
            model_name='workflowtemplatephase',
            name='qa_rollback_target_order',
            field=models.PositiveIntegerField(blank=True, help_text='Phase order to rollback to if QA/Final QA fails this phase (must be lower number)', null=True),
        ),
        migrations.AlterField(
            model_name='productionphase',
            name='can_rollback_to',
            field=models.ForeignKey(blank=True, help_text='Phase to rollback to if QC fails this phase', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_rollback_from', to='workflow.productionphase'),
        ),
        migrations.AlterField(
            model_name='workflowtemplatephase',
            name='rollback_target_order',
            field=models.PositiveIntegerField(blank=True, help_text='Phase order to rollback to if QC fails this phase (must be lower number)', null=True),
        ),
    ]
