# Generated by Django 5.2.8 on 2026-02-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0029_add_qa_rollback_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchphaseexecution',
            name='template_section_completed',
            field=models.BooleanField(default=False),
        ),
    ]
