# Generated by Django 5.2.8 on 2026-03-05 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0030_batchphaseexecution_template_section_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batchphaseexecution',
            name='beginning_lc_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beginning_lc_approved_phases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchphaseexecution',
            name='beginning_lc_approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchphaseexecution',
            name='beginning_lc_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('not_started', 'Not Started'), ('operator_filled', 'Operator Filled'), ('qa_approved', 'QA Approved'), ('qa_rejected', 'QA Rejected')], default='not_started', help_text='Beginning LC: Operator fills → Supervisor signs → QA approves → Start activates', max_length=20),
        ),
        migrations.AddField(
            model_name='batchphaseexecution',
            name='ending_lc_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ending_lc_approved_phases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchphaseexecution',
            name='ending_lc_approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchphaseexecution',
            name='ending_lc_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('not_started', 'Not Started'), ('operator_filled', 'Operator Filled'), ('qa_approved', 'QA Approved'), ('qa_rejected', 'QA Rejected')], default='not_started', help_text='Ending LC: After process data filled, same signing flow → Complete activates', max_length=20),
        ),
    ]
