# Generated by Django 5.2.8 on 2026-03-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0031_add_lc_status_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchphaseexecution',
            name='beginning_lc_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('not_started', 'Not Started'), ('operator_filled', 'Operator Filled'), ('qa_approved', 'QA Approved'), ('qa_rejected', 'QA Rejected')], default='not_required', help_text='Beginning LC: Operator fills → Supervisor signs → QA approves → Start activates', max_length=20),
        ),
        migrations.AlterField(
            model_name='batchphaseexecution',
            name='ending_lc_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('not_started', 'Not Started'), ('operator_filled', 'Operator Filled'), ('qa_approved', 'QA Approved'), ('qa_rejected', 'QA Rejected')], default='not_required', help_text='Ending LC: After process data filled, same signing flow → Complete activates', max_length=20),
        ),
    ]
