# Generated by Django 5.2.8 on 2026-03-06 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0033_update_existing_lc_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batchphaseexecution',
            name='process_signing_completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_signing_completed_phases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchphaseexecution',
            name='process_signing_completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchphaseexecution',
            name='process_signing_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('not_started', 'Not Started'), ('operator_filled', 'Operator Filled'), ('qa_signed', 'QA Signed')], default='not_required', help_text='Operator fills process tables + signs → submits for QA → QA signs their columns → Complete', max_length=20),
        ),
        migrations.AddField(
            model_name='batchphaseexecution',
            name='process_signing_submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_signing_submitted_phases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchphaseexecution',
            name='process_signing_submitted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
