# Generated by Django 4.2.7 on 2026-09-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0036_alter_productionphase_phase_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionphase',
            name='phase_name',
            field=models.CharField(choices=[('bmr_creation', 'BMR Creation'), ('regulatory_approval', 'Regulatory Approval'), ('material_dispensing', 'Material Dispensing'), ('quality_control', 'Quality Control'), ('post_compression_qc', 'Post-Compression QC'), ('post_mixing_qc', 'Post-Mixing QC'), ('post_blending_qc', 'Post-Blending QC'), ('packaging_material_release', 'Packaging Material Release'), ('secondary_packaging', 'Secondary Packaging'), ('final_qa', 'Final QA'), ('finished_goods_store', 'Finished Goods Store'), ('mixing', 'Mixing'), ('tube_filling', 'Tube Filling'), ('granulation', 'Granulation'), ('blending', 'Blending'), ('compression', 'Compression'), ('sorting', 'Sorting'), ('coating', 'Coating'), ('post_coating_sorting', 'Post-Coating Sorting'), ('blister_packing', 'Blister Packing'), ('bulk_packing', 'Bulk Packing'), ('drying', 'Drying'), ('filling', 'Filling')], max_length=30),
        ),
    ]
