# Generated by Django 5.2.6 on 2025-10-06 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmr', '0003_rawmaterialrelease_remove_bmr_batch_size_and_more'),
        ('products', '0006_remove_product_maximum_batch_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BMRRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('required_date', models.DateField(help_text='Date when the BMR is required')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('reason', models.TextField(help_text='Reason for requesting the BMR')),
                ('quantity_required', models.PositiveIntegerField(help_text='Quantity required for production')),
                ('quantity_unit', models.CharField(help_text='Unit of measurement for quantity (e.g., kg, tablets, etc.)', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_bmr_requests', to=settings.AUTH_USER_MODEL)),
                ('bmr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bmr_requests', to='bmr.bmr')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bmr_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BMR Request',
                'verbose_name_plural': 'BMR Requests',
                'ordering': ['-request_date'],
            },
        ),
    ]
