# Generated by Django 5.2.6 on 2025-10-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmr', '0004_bmrrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmr',
            name='manufacturing_date',
            field=models.DateField(help_text='Enter the manufacturing date for this batch', null=True),
        ),
    ]
