# Generated by Django 4.2.7 on 2025-11-11 11:10

import bmr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmr', '0005_bmr_manufacturing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmr',
            name='batch_number',
            field=models.CharField(help_text='Enter batch number in format XXXYYYY (e.g., 3332025)', max_length=10, unique=True, validators=[bmr.models.validate_batch_number]),
        ),
    ]
