# Generated by Django 4.2.7 on 2025-11-18 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmr', '0006_alter_bmr_batch_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmrrequest',
            name='bmr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bmr_requests', to='bmr.bmr'),
        ),
    ]
