# Generated by Django 5.2.8 on 2026-02-11 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmr', '0009_add_bmrtemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BMRTemplateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('section_type', models.CharField(choices=[('info', 'Information Section'), ('form', 'Form Section'), ('table', 'Table Section'), ('signature', 'Signature Section'), ('divider', 'Page Break/Divider')], default='info', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('page_number', models.PositiveIntegerField(default=1, help_text='Which page this section appears on')),
                ('columns', models.PositiveIntegerField(default=1, help_text='Number of columns (1-4)')),
                ('width_class', models.CharField(default='col-12', help_text='Bootstrap column class', max_length=20)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='bmr.bmrtemplate')),
            ],
            options={
                'verbose_name': 'BMR Template Section',
                'verbose_name_plural': 'BMR Template Sections',
                'ordering': ['page_number', 'order'],
            },
        ),
        migrations.CreateModel(
            name='BMRTemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Text Area'), ('number', 'Number Input'), ('decimal', 'Decimal Number'), ('date', 'Date Input'), ('datetime', 'Date & Time Input'), ('time', 'Time Input'), ('select', 'Dropdown Select'), ('checkbox', 'Checkbox'), ('radio', 'Radio Buttons'), ('signature', 'Digital Signature'), ('static_text', 'Static Text/Label'), ('image', 'Image Upload'), ('calculated', 'Calculated Field')], default='text', max_length=20)),
                ('data_source', models.CharField(choices=[('manual', 'Manual Entry'), ('bmr.bmr_number', 'BMR Number'), ('bmr.batch_number', 'Batch Number'), ('bmr.product.product_name', 'Product Name'), ('bmr.product.generic_name', 'Generic Name'), ('bmr.batch_size', 'Batch Size'), ('bmr.manufacturing_date', 'Manufacturing Date'), ('bmr.created_date', 'Created Date'), ('bmr.status', 'BMR Status'), ('bmr.created_by.get_full_name', 'Created By'), ('bmr.approved_by.get_full_name', 'Approved By'), ('ingredient_table', 'Ingredient Table Data'), ('workflow_status', 'Workflow Status'), ('signatures', 'Electronic Signatures'), ('current_user.get_full_name', 'Current User Name'), ('current_date', 'Current Date'), ('current_time', 'Current Time')], default='manual', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=False)),
                ('is_readonly', models.BooleanField(default=False)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('help_text', models.TextField(blank=True)),
                ('default_value', models.TextField(blank=True)),
                ('min_length', models.PositiveIntegerField(blank=True, null=True)),
                ('max_length', models.PositiveIntegerField(blank=True, null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('regex_pattern', models.CharField(blank=True, help_text='Regular expression for validation', max_length=500)),
                ('field_options', models.JSONField(blank=True, default=list, help_text='Options for select/radio fields as JSON array')),
                ('width_class', models.CharField(default='col-12', max_length=20)),
                ('css_classes', models.CharField(blank=True, max_length=200)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='bmr.bmrtemplatesection')),
            ],
            options={
                'verbose_name': 'BMR Template Field',
                'verbose_name_plural': 'BMR Template Fields',
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='BMRTemplateTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('data_source', models.CharField(help_text='Source of table data (e.g. ingredient_table)', max_length=100)),
                ('is_editable', models.BooleanField(default=False, help_text='Can users add/edit rows?')),
                ('show_row_numbers', models.BooleanField(default=True)),
                ('max_rows', models.PositiveIntegerField(blank=True, help_text='Maximum allowed rows', null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='bmr.bmrtemplatesection')),
            ],
            options={
                'verbose_name': 'BMR Template Table',
                'verbose_name_plural': 'BMR Template Tables',
            },
        ),
        migrations.CreateModel(
            name='BMRTemplateTableColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Text Area'), ('number', 'Number Input'), ('decimal', 'Decimal Number'), ('date', 'Date Input'), ('datetime', 'Date & Time Input'), ('time', 'Time Input'), ('select', 'Dropdown Select'), ('checkbox', 'Checkbox'), ('radio', 'Radio Buttons'), ('signature', 'Digital Signature'), ('static_text', 'Static Text/Label'), ('image', 'Image Upload'), ('calculated', 'Calculated Field')], default='text', max_length=20)),
                ('data_source', models.CharField(blank=True, help_text="Row field to display (e.g. 'description', 'total_batch_quantity')", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('width_percentage', models.PositiveIntegerField(default=10, help_text='Column width as percentage')),
                ('is_sortable', models.BooleanField(default=False)),
                ('is_editable', models.BooleanField(default=False)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='bmr.bmrtemplatetable')),
            ],
            options={
                'verbose_name': 'Table Column',
                'verbose_name_plural': 'Table Columns',
                'ordering': ['table', 'order'],
            },
        ),
        migrations.CreateModel(
            name='BMRFormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('file_value', models.FileField(blank=True, null=True, upload_to='bmr_uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bmr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_data', to='bmr.bmr')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bmr_form_entries', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmr.bmrtemplatefield')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmr.bmrtemplatesection')),
            ],
            options={
                'verbose_name': 'BMR Form Data',
                'verbose_name_plural': 'BMR Form Data',
                'unique_together': {('bmr', 'section', 'field')},
            },
        ),
    ]
