# Generated by Django 4.2.7 on 2026-03-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmr', '0011_bmrtemplate_product_type_bmrtemplatesection_phase_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmrtemplate',
            name='product_type',
            field=models.CharField(blank=True, choices=[('', 'Universal (all types)'), ('tablet', 'Tablet (Coated / Normal)'), ('tablet_normal', 'Tablet Normal (legacy)'), ('tablet_type_2', 'Tablet Type 2 (Bulk Packing)'), ('ointment', 'Ointment'), ('capsule', 'Capsule')], db_index=True, default='', help_text='The product type this template applies to. Leave blank for a universal template.', max_length=20),
        ),
        migrations.AlterField(
            model_name='bmrtemplatefield',
            name='data_source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('bmr.bmr_number', 'BMR Number'), ('bmr.batch_number', 'Batch Number'), ('bmr.product.product_name', 'Product Name'), ('bmr.product.generic_name', 'Generic Name'), ('bmr.batch_size', 'Batch Size'), ('bmr.manufacturing_date', 'Manufacturing Date'), ('bmr.created_date', 'Created Date'), ('bmr.status', 'BMR Status'), ('bmr.created_by.get_full_name', 'Created By'), ('bmr.approved_by.get_full_name', 'Approved By'), ('ingredient_table', 'Ingredient Table Data'), ('ingredient_table_totals_rows', 'Ingredient Totals Rows'), ('signature_rows', 'Signature Rows'), ('workflow_status', 'Workflow Status'), ('signatures', 'Electronic Signatures'), ('current_user.get_full_name', 'Current User Name'), ('current_date', 'Current Date'), ('current_time', 'Current Time')], default='manual', max_length=100),
        ),
        migrations.AlterField(
            model_name='bmrtemplatesection',
            name='section_type',
            field=models.CharField(choices=[('info', 'Information Section'), ('form', 'Form Section'), ('table', 'Table Section'), ('signature', 'Signature Section'), ('divider', 'Page Break/Divider'), ('line_clearance', 'Line Clearance'), ('process_steps', 'Process Steps'), ('qa_report', 'QA Report'), ('yield_reconciliation', 'Yield Reconciliation'), ('ipc_table', 'IPC Table (In-Process Control)'), ('coding_control', 'Coding Control / Secondary IPC'), ('equipment_setup', 'Equipment Setup'), ('material_table', 'Material Table (Store Release / Dispensing)')], default='info', max_length=25),
        ),
    ]
