# Generated by Django 4.2.7 on 2026-03-25 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_productrevisionhistory'),
        ('bmr', '0012_material_table_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmrtemplate',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Link to a specific product. If set, this template is used exclusively for that product, overriding the product_type template.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bmr_templates', to='products.product'),
        ),
    ]
