# Generated by Django 4.2.7 on 2026-03-26 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_productrevisionhistory'),
        ('bmr', '0013_bmrtemplate_product_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='YieldReconciliationRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('blending', 'Blending / Lubrication'), ('capsule_filling', 'Capsule Filling'), ('blistering', 'Blistering / Primary Packaging'), ('inspection', 'Inspection & Sorting')], db_index=True, max_length=40)),
                ('row_key', models.CharField(help_text='Short letter key shown in the "Steps" column (e.g. A, B, F.)', max_length=5)),
                ('label', models.CharField(help_text='Description shown in the "Descriptions" column', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yield_rows', to='products.product')),
            ],
            options={
                'verbose_name': 'Yield Reconciliation Row',
                'verbose_name_plural': 'Yield Reconciliation Rows',
                'ordering': ['phase', 'order'],
            },
        ),
        migrations.CreateModel(
            name='WeightRangeLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('capsule_filling', 'Capsule Filling'), ('compression', 'Tablet Compression')], default='capsule_filling', max_length=40)),
                ('category', models.CharField(help_text='Category label, e.g. ">105%"', max_length=30)),
                ('percent_of_target', models.CharField(help_text='Percentage value, e.g. ">105%"', max_length=30)),
                ('tolerance_code', models.CharField(help_text='Code shown in Tolerance column, e.g. ">+T2"', max_length=20)),
                ('action', models.CharField(help_text='Action text, e.g. "Action", "Alert", "Good"', max_length=30)),
                ('is_highlighted', models.BooleanField(default=False, help_text='Tick for the target/nominal row (rendered with green background)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_range_limits', to='products.product')),
            ],
            options={
                'verbose_name': 'Weight Range Limit',
                'verbose_name_plural': 'Weight Range Limits',
                'ordering': ['phase', 'order'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('general', 'General Equipment List (Page 5)'), ('blending', 'Blending / Lubrication'), ('capsule_filling', 'Capsule Filling'), ('inspection', 'Inspection & Sorting'), ('packaging', 'Packaging / Blistering')], db_index=True, max_length=40)),
                ('equipment_name', models.CharField(max_length=120)),
                ('equipment_id', models.CharField(blank=True, default='—', help_text='Equipment ID / mark number (e.g. PN-06)', max_length=30)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the phase')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_entries', to='products.product')),
            ],
            options={
                'verbose_name': 'Equipment Entry',
                'verbose_name_plural': 'Equipment Entries',
                'ordering': ['phase', 'order'],
            },
        ),
        migrations.CreateModel(
            name='BMRProcedureStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('blending', 'Blending / Lubrication'), ('capsule_filling', 'Capsule Filling'), ('inspection', 'Inspection & Sorting'), ('packaging', 'Primary Packaging'), ('secondary_packaging', 'Secondary Packaging')], db_index=True, max_length=40)),
                ('step_number', models.CharField(help_text='Display step label: "1", "2", "2a", "Step 3" etc.', max_length=10)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_steps', to='products.product')),
            ],
            options={
                'verbose_name': 'BMR Procedure Step',
                'verbose_name_plural': 'BMR Procedure Steps',
                'ordering': ['phase', 'order'],
            },
        ),
    ]
