# Generated by Django 4.2.7 on 2026-03-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmr', '0014_product_content_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmr',
            name='expiry_date',
            field=models.DateField(help_text='Enter the expiry date for this batch', null=True),
        ),
        migrations.AlterField(
            model_name='bmrprocedurestep',
            name='phase',
            field=models.CharField(choices=[('blending', 'Blending / Lubrication'), ('capsule_filling', 'Capsule Filling'), ('mixing', 'Mixing'), ('tube_filling', 'Tube Filling'), ('inspection', 'Inspection & Sorting'), ('packaging', 'Primary Packaging'), ('secondary_packaging', 'Secondary Packaging')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='equipmententry',
            name='phase',
            field=models.CharField(choices=[('general', 'General Equipment List (Page 5)'), ('dispensing', 'Dispensing'), ('mixing', 'Mixing'), ('tube_filling', 'Tube Filling'), ('granulation_1', 'Granulation 1'), ('granulation_2', 'Granulation 2'), ('compression', 'Compression'), ('blending', 'Blending / Lubrication'), ('ipqc_lab', 'IPQC Lab'), ('visual_inspection', 'Visual Inspection & Sorting'), ('blister_packing', 'Blister Packing'), ('strip_packing', 'Strip Packing'), ('capsule_filling', 'Capsule Filling'), ('inspection', 'Inspection & Sorting'), ('packaging', 'Packaging / Blistering')], db_index=True, max_length=40),
        ),
    ]
