# Generated by Django 4.2.7 on 2026-05-26 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_product_capsule_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bmr', '0015_bmr_expiry_date_alter_bmrprocedurestep_phase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMRIssuanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sop_reference', models.CharField(default='NDA/QA/020/SOP', help_text='Standard Operating Procedure reference number', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(help_text='Product that this log tracks', on_delete=django.db.models.deletion.CASCADE, related_name='issuance_log', to='products.product')),
            ],
            options={
                'verbose_name': 'BMR Issuance Log',
                'verbose_name_plural': 'BMR Issuance Logs',
                'ordering': ['product__product_name'],
            },
        ),
        migrations.CreateModel(
            name='BMRIssuanceLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.PositiveIntegerField(help_text="Entry number within this product's log")),
                ('issue_date', models.DateField(help_text='Date when QA approved the BMR request')),
                ('active_ingredients', models.JSONField(default=list, help_text='List of active ingredients with AR numbers')),
                ('issued_by_signature', models.CharField(blank=True, help_text='Electronic signature of QA officer', max_length=200)),
                ('issued_by_date', models.DateTimeField(blank=True, help_text='Date and time when QA signed', null=True)),
                ('received_by_signature', models.CharField(blank=True, help_text='Electronic signature of Production Officer', max_length=200)),
                ('received_by_date', models.DateTimeField(blank=True, help_text='Date and time when Production Officer signed', null=True)),
                ('submitted_by_signature', models.CharField(blank=True, help_text='Electronic signature of QA officer (final submission)', max_length=200)),
                ('submitted_by_date', models.DateTimeField(blank=True, help_text='Date and time when QA signed final submission', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bmr', models.OneToOneField(help_text='BMR record for this batch', on_delete=django.db.models.deletion.CASCADE, related_name='issuance_entry', to='bmr.bmr')),
                ('issuance_log', models.ForeignKey(help_text='Parent issuance log for this product', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='bmr.bmrissuancelog')),
                ('issued_by', models.ForeignKey(help_text='QA officer who approved the production request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_bmr_entries', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, help_text='Production Officer who received the BMR approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_bmr_entries', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, help_text='QA officer who signs after packing yield reconciliation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_bmr_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BMR Issuance Log Entry',
                'verbose_name_plural': 'BMR Issuance Log Entries',
                'ordering': ['issuance_log', 'entry_number'],
                'unique_together': {('issuance_log', 'entry_number')},
            },
        ),
    ]
