# Generated by Django 4.2.7 on 2026-05-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmr', '0016_bmrissuancelog_bmrissuancelogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmrissuancelogentry',
            name='pack_size',
            field=models.CharField(blank=True, help_text="Final packed quantity (e.g., '1000 blisters')", max_length=100),
        ),
        migrations.AddField(
            model_name='bmrissuancelogentry',
            name='release_date',
            field=models.DateField(blank=True, help_text='Date when batch was released after final QA approval', null=True),
        ),
        migrations.AddField(
            model_name='bmrissuancelogentry',
            name='remarks',
            field=models.TextField(blank=True, help_text='Any additional notes or comments'),
        ),
    ]
