# Generated by Django 4.2.7 on 2026-05-26 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bmr', '0017_bmrissuancelogentry_pack_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmrissuancelogentry',
            name='received_back_by',
            field=models.ForeignKey(blank=True, help_text='QA officer who receives back the completed batch documentation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_back_bmr_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bmrissuancelogentry',
            name='received_back_by_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when QA received back documentation', null=True),
        ),
        migrations.AddField(
            model_name='bmrissuancelogentry',
            name='received_back_by_signature',
            field=models.CharField(blank=True, help_text='Electronic signature of QA officer receiving back documentation', max_length=200),
        ),
    ]
