# Generated by Django 4.2.7 on 2026-06-02 08:14

import bmr.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0035_product_capsule_type'),
        ('bmr', '0018_bmrissuancelogentry_received_back_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBMR',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('bmr_number', models.CharField(db_index=True, max_length=20)),
                ('batch_number', models.CharField(help_text='Enter batch number in format XXXYYYY (e.g., 3332025)', max_length=10, validators=[bmr.models.validate_batch_number])),
                ('manufacturing_date', models.DateField(help_text='Enter the manufacturing date for this batch', null=True)),
                ('expiry_date', models.DateField(help_text='Enter the expiry date for this batch', null=True)),
                ('actual_batch_size', models.DecimalField(blank=True, decimal_places=2, help_text='Actual batch size (if different from standard product batch size)', max_digits=10, null=True)),
                ('actual_batch_size_unit', models.CharField(blank=True, help_text='Unit for actual batch size (inherits from product if not specified)', max_length=20)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('planned_start_date', models.DateTimeField(blank=True, null=True)),
                ('planned_completion_date', models.DateTimeField(blank=True, null=True)),
                ('actual_start_date', models.DateTimeField(blank=True, null=True)),
                ('actual_completion_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_production', 'In Production'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('manufacturing_instructions', models.TextField(blank=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('in_process_controls', models.TextField(blank=True)),
                ('quality_checks_required', models.TextField(blank=True)),
                ('qa_comments', models.TextField(blank=True)),
                ('regulatory_comments', models.TextField(blank=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.product')),
                ('template', models.ForeignKey(blank=True, db_constraint=False, help_text='Template structure used to render this BMR', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bmr.bmrtemplate')),
            ],
            options={
                'verbose_name': 'historical Batch Manufacturing Record',
                'verbose_name_plural': 'historical Batch Manufacturing Records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
