# Generated by Django 4.2.7 on 2026-07-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmr', '0019_historicalbmr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalBMR',
        ),
    ]
