# Generated by Django 5.2.6 on 2025-10-06 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_add_packaging_size_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='maximum_batch_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='minimum_batch_size',
        ),
    ]
