# Generated by Django 5.2.8 on 2025-12-01 10:42

import workflow.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_maximum_batch_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=workflow.constants.get_product_type_choices, max_length=20),
        ),
    ]
