# Generated by Django 5.2.8 on 2025-12-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('ointment', 'Ointment'), ('tablet', 'Tablet'), ('capsule', 'Capsule')], max_length=20),
        ),
    ]
