# Generated by Django 5.2.8 on 2026-02-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='assay_max_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=105.0, help_text='Maximum assay percentage of label claim (e.g., 105.0%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='assay_min_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=95.0, help_text='Minimum assay percentage of label claim (e.g., 95.0%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='average_weight_uncoated',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Average weight in mg (e.g., 591.1mg for uncoated tablets)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='blending_time_minutes',
            field=models.DecimalField(blank=True, decimal_places=1, default=20.0, help_text='Blending time in minutes (e.g., 20 min)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_name',
            field=models.CharField(blank=True, help_text='Brand/Trade name if different from product name', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='color_description',
            field=models.CharField(blank=True, help_text='Product color (e.g., White)', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='diameter_nominal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Nominal diameter in mm (e.g., 12.5)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='diameter_tolerance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.2, help_text='Diameter tolerance ± in mm (e.g., ±0.2)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='disintegration_time_max',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Maximum disintegration time in minutes (e.g., NMT 15 min)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dissolution_spec',
            field=models.CharField(blank=True, help_text='Dissolution specification (e.g., Not Less than 70% for each Tablet)', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='dry_mixing_fast_time',
            field=models.DecimalField(blank=True, decimal_places=1, default=5.0, help_text='Dry mixing fast speed time in minutes (e.g., 5 min)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dry_mixing_slow_time',
            field=models.DecimalField(blank=True, decimal_places=1, default=10.0, help_text='Dry mixing slow speed time in minutes (e.g., 10 min)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='drying_temperature',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Standard drying temperature in °C (e.g., 70°C)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='drying_time_minutes',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Standard drying time in minutes (e.g., 45 min)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='friability_max',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, help_text='Maximum friability % (e.g., NMT 1.0%)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='hardness_max',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Maximum hardness in kg/cm² (e.g., 8)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='hardness_min',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Minimum hardness in kg/cm² (e.g., 4)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='label_claim',
            field=models.TextField(blank=True, help_text='Complete label claim (e.g., Each Kamadol Tablet Contains: Paracetamol BP 500 mg)'),
        ),
        migrations.AddField(
            model_name='product',
            name='lod_max_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=3.6, help_text='Maximum Loss on Drying % (e.g., 3.60%)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='lod_min_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.6, help_text='Minimum Loss on Drying % (e.g., 1.60%)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='lower_punch_description',
            field=models.CharField(blank=True, help_text='Lower punch description (e.g., Flat Beveled, Plain)', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='magnesium_stearate_sieve_mesh',
            field=models.IntegerField(blank=True, default=40, help_text='Mesh size for Magnesium Stearate sifting (e.g., #40)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='market_type',
            field=models.CharField(blank=True, default='Domestic/Local', help_text='Target market (e.g., Domestic/Local, Export)', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='max_humidity_percentage',
            field=models.DecimalField(blank=True, decimal_places=1, default=65.0, help_text='Maximum relative humidity % (e.g., 65%)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='max_temperature_celsius',
            field=models.DecimalField(blank=True, decimal_places=1, default=28.0, help_text='Maximum manufacturing temperature in °C (e.g., NMT 28°C)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='max_yield_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=102.0, help_text='Maximum acceptable yield % (e.g., 102%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mfg_license_number',
            field=models.CharField(blank=True, help_text='Manufacturing license number (e.g., NDA/MAL/HDP/1887)', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='milling_sieve_size',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Milling sieve size in mm (e.g., 4mm)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='min_humidity_percentage',
            field=models.DecimalField(blank=True, decimal_places=1, default=40.0, help_text='Minimum relative humidity % (e.g., 40%)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='min_yield_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=98.0, help_text='Minimum acceptable yield % (e.g., 98%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='punch_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Punch size in mm (e.g., 12.5mm)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='punch_type',
            field=models.CharField(blank=True, help_text='Punch type (e.g., D-TOOLING, B-TOOLING)', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='shelf_life_years',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Shelf life in years (e.g., 3 years)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='special_instructions',
            field=models.TextField(blank=True, help_text='Any special manufacturing instructions specific to this product'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_conditions',
            field=models.TextField(blank=True, help_text='Storage requirements (e.g., Store in a cool & dry place. Protect from direct light, heat and moisture.)'),
        ),
        migrations.AddField(
            model_name='product',
            name='tablet_appearance_trade',
            field=models.TextField(blank=True, help_text="Tablet appearance for Trade market (e.g., White round flat tablets embossed 'P500' above and 'KPI' below)"),
        ),
        migrations.AddField(
            model_name='product',
            name='tablet_appearance_ug',
            field=models.TextField(blank=True, help_text='Tablet appearance for UG market if different'),
        ),
        migrations.AddField(
            model_name='product',
            name='thickness_nominal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Nominal thickness in mm (e.g., 4.35)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='thickness_tolerance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.3, help_text='Thickness tolerance ± in mm (e.g., ±0.3)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='upper_punch_description',
            field=models.CharField(blank=True, help_text='Upper punch description (e.g., Flat Beveled, Embossed P500 over B/L and KPI under B/L)', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_tolerance_percentage',
            field=models.DecimalField(blank=True, decimal_places=1, default=5.0, help_text='Weight tolerance ±% (default: ±5%)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wet_mixing_fast_time',
            field=models.DecimalField(blank=True, decimal_places=1, default=3.0, help_text='Wet mixing fast speed time in minutes (e.g., 3 min)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wet_mixing_slow_time',
            field=models.DecimalField(blank=True, decimal_places=1, default=3.0, help_text='Wet mixing slow speed time in minutes (e.g., 3 min)', max_digits=5, null=True),
        ),
    ]
