# Generated by Django 5.2.8 on 2026-02-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_add_product_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bmr_revision_no',
            field=models.CharField(blank=True, help_text='BMR Revision Number (e.g., 03)', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='generic_name',
            field=models.CharField(blank=True, help_text='Generic pharmaceutical name (e.g., Paracetamol Tablets BP 500mg)', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='mfr_number',
            field=models.CharField(blank=True, help_text='Master Formula Record Number (e.g., KPI/MFR/003/00)', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_size_1_code',
            field=models.CharField(blank=True, help_text='Pack size 1 code (e.g., KMD1TB)', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_size_1_description',
            field=models.CharField(blank=True, help_text='Pack size 1 description (e.g., 10x10 Blisters)', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_size_2_code',
            field=models.CharField(blank=True, help_text='Pack size 2 code (e.g., KMD2TB)', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_size_2_description',
            field=models.CharField(blank=True, help_text='Pack size 2 description (e.g., 100 Blisters X 10 Tablets)', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_size_3_code',
            field=models.CharField(blank=True, help_text='Pack size 3 code (e.g., KMD3TJ)', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_size_3_description',
            field=models.CharField(blank=True, help_text="Pack size 3 description (e.g., 500's)", max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_size_4_code',
            field=models.CharField(blank=True, help_text='Pack size 4 code (e.g., KMD4TJ)', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_size_4_description',
            field=models.CharField(blank=True, help_text="Pack size 4 description (e.g., 1000's)", max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, help_text='Product code for identification', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='reference_sop_number',
            field=models.CharField(blank=True, help_text='Reference SOP Number (e.g., QAD/022/01)', max_length=50),
        ),
    ]
