# Generated by Django 5.2.8 on 2026-02-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_bmr_revision_no_product_generic_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='general_instructions',
            field=models.JSONField(blank=True, default=list, help_text='List of strings for General Instructions (Page 7)'),
        ),
        migrations.AddField(
            model_name='product',
            name='general_sops',
            field=models.JSONField(blank=True, default=list, help_text="List of dictionaries {'sn': '1', 'title': '...', 'sop_no': '...'} for General SOPs (Page 7)"),
        ),
        migrations.AddField(
            model_name='product',
            name='safety_precautions',
            field=models.JSONField(blank=True, default=list, help_text='List of strings for Safety Precautions (Page 7)'),
        ),
    ]
