# Generated by Django 5.2.8 on 2026-02-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_general_instructions_product_general_sops_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dispensing_clearance_end_items',
            field=models.JSONField(blank=True, default=list, help_text='List of strings for Dispensing Line Clearance Ending Activities (Page 8)'),
        ),
        migrations.AddField(
            model_name='product',
            name='dispensing_clearance_start_items',
            field=models.JSONField(blank=True, default=list, help_text='List of strings for Dispensing Line Clearance Beginning Activities (Page 8)'),
        ),
    ]
