# Generated by Django 5.2.8 on 2026-02-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_dispensing_clearance_end_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='granulation_steps',
            field=models.JSONField(blank=True, default=list, help_text='List of strings for Granulation/Mixing Process Steps (Page 9)'),
        ),
    ]
