# Generated by Django 5.2.8 on 2026-02-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_granulation_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='granulation_clearance_end_items',
            field=models.JSONField(blank=True, default=list, help_text='List of strings for Granulation Line Clearance Ending Activities (Page 10)'),
        ),
        migrations.AddField(
            model_name='product',
            name='granulation_clearance_start_items',
            field=models.JSONField(blank=True, default=list, help_text='List of strings for Granulation Line Clearance Beginning Activities (Page 10)'),
        ),
    ]
