# Generated by Django 5.2.8 on 2026-02-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_granulation_clearance_end_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dry_mixing_instructions',
            field=models.JSONField(blank=True, default=list, help_text='List of strings for Dry Mixing instructions (Page 11)'),
        ),
        migrations.AddField(
            model_name='product',
            name='granulation_lot_count',
            field=models.PositiveIntegerField(default=4, help_text='Number of lots for granulation (Page 11)'),
        ),
        migrations.AddField(
            model_name='product',
            name='wet_mixing_instructions',
            field=models.JSONField(blank=True, default=list, help_text='List of strings for Wet Mixing instructions (Page 11)'),
        ),
    ]
