# Generated by Django 5.2.8 on 2026-02-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_dry_mixing_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='drying_instructions',
            field=models.JSONField(blank=True, default=list, help_text='List of strings for Drying instructions (Page 12)'),
        ),
    ]
