# Generated by Django 5.2.8 on 2026-02-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_drying_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='final_drying_instructions',
            field=models.JSONField(blank=True, default=list, help_text='List of strings for Final Drying instructions (Page 13)'),
        ),
        migrations.AddField(
            model_name='product',
            name='lod_limits',
            field=models.CharField(default='1.60-3.60', help_text='LOD Limits in % (e.g. 1.60-3.60)', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='yield_drum_count',
            field=models.PositiveIntegerField(default=10, help_text='Number of rows for Yield/Drum table (Page 14)'),
        ),
    ]
