# Generated by Django 5.2.8 on 2026-02-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_final_drying_instructions_product_lod_limits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='yield_limit_max',
            field=models.DecimalField(decimal_places=2, default=102.0, help_text='Maximum permissible yield % (Default: 102.00)', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='yield_limit_min',
            field=models.DecimalField(decimal_places=2, default=98.0, help_text='Minimum permissible yield % (Default: 98.00)', max_digits=5),
        ),
    ]
