# Generated by Django 5.2.8 on 2026-02-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_yield_limit_max_product_yield_limit_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='blending_time',
            field=models.CharField(default='20 minutes', help_text='Blending/Mixing time (e.g. 20 minutes)', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='magnesium_stearate_qty',
            field=models.CharField(default='256gm', help_text='Quantity of Magnesium Stearate (e.g. 256gm)', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='sieve_size_lubrication',
            field=models.CharField(default='#40', help_text='Mesh size for Lubrication (e.g. #40)', max_length=50),
        ),
    ]
