# Generated by Django 5.2.8 on 2026-02-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_blending_time_product_magnesium_stearate_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='compression_rh_limit_max',
            field=models.DecimalField(blank=True, decimal_places=1, default=65.0, help_text='Maximum relative humidity for compression area in % (e.g. 65.0)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='compression_rh_limit_min',
            field=models.DecimalField(blank=True, decimal_places=1, default=40.0, help_text='Minimum relative humidity for compression area in % (e.g. 40.0)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='compression_temperature_limit',
            field=models.DecimalField(blank=True, decimal_places=1, default=28.0, help_text='Maximum temperature for compression area in °C (e.g. 28.0)', max_digits=4, null=True),
        ),
    ]
