# Generated by Django 5.2.8 on 2026-02-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_product_compression_rh_limit_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lower_punch_description_ug',
            field=models.CharField(blank=True, help_text='Lower punch description for UG market', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='punch_shape_trade',
            field=models.CharField(blank=True, help_text='Punch shape for Trade (e.g. Round flat)', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='punch_shape_ug',
            field=models.CharField(blank=True, help_text='Punch shape for UG (e.g. Round flat)', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='punch_size_ug',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Punch size for UG market in mm (if different)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='upper_punch_description_ug',
            field=models.CharField(blank=True, help_text='Upper punch description for UG market', max_length=200),
        ),
    ]
