# Generated by Django 5.2.8 on 2026-02-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_product_lower_punch_description_ug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='compression_instructions',
            field=models.JSONField(blank=True, default=list, help_text='List of strings for Compression Setting Instructions (Page 23)'),
        ),
    ]
