# Generated by Django 5.2.8 on 2026-02-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_compression_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='standard_weight_tolerance_percentage',
            field=models.DecimalField(blank=True, decimal_places=1, default=2.0, help_text='Standard Weight tolerance ±% (default: ±2%)', max_digits=4, null=True),
        ),
    ]
