# Generated by Django 5.2.8 on 2026-03-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_product_standard_weight_tolerance_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='blending_clearance_end_items',
            field=models.JSONField(blank=True, default=list, help_text='List of strings for Blending Line Clearance Ending Activities (Page 16)'),
        ),
        migrations.AddField(
            model_name='product',
            name='blending_clearance_start_items',
            field=models.JSONField(blank=True, default=list, help_text='List of strings for Blending Line Clearance Beginning Activities (Page 16)'),
        ),
        migrations.AddField(
            model_name='product',
            name='compression_clearance_end_items',
            field=models.JSONField(blank=True, default=list, help_text='List of strings for Compression Line Clearance Ending Activities (Page 20)'),
        ),
        migrations.AddField(
            model_name='product',
            name='compression_clearance_start_items',
            field=models.JSONField(blank=True, default=list, help_text='List of strings for Compression Line Clearance Beginning Activities (Page 20)'),
        ),
        migrations.AddField(
            model_name='product',
            name='packing_clearance_end_items',
            field=models.JSONField(blank=True, default=list, help_text='List of strings for Packaging Line Clearance Ending Activities (Page 42)'),
        ),
        migrations.AddField(
            model_name='product',
            name='packing_clearance_start_items',
            field=models.JSONField(blank=True, default=list, help_text='List of strings for Packaging Line Clearance Beginning Activities (Page 42)'),
        ),
        migrations.AddField(
            model_name='product',
            name='sorting_clearance_end_items',
            field=models.JSONField(blank=True, default=list, help_text='List of strings for Sorting/Inspection Line Clearance Ending Activities (Page 38)'),
        ),
        migrations.AddField(
            model_name='product',
            name='sorting_clearance_start_items',
            field=models.JSONField(blank=True, default=list, help_text='List of strings for Sorting/Inspection Line Clearance Beginning Activities (Page 38)'),
        ),
    ]
