# Generated by Django 5.2.8 on 2026-03-11 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_add_blending_compression_sorting_packing_lc_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(help_text='Item code e.g. KMD 203TB', max_length=50)),
                ('item_description', models.CharField(help_text='Full item description', max_length=200)),
                ('units', models.CharField(choices=[('Kg', 'Kg'), ('PCS', 'PCS'), ('Roll', 'Roll'), ('Box', 'Box'), ('Litre', 'Litre')], default='PCS', max_length=20)),
                ('pack_type', models.CharField(choices=[('blister', 'Blister Pack'), ('bulk', 'Bulk Pack'), ('both', 'Both / All Pack Types')], default='blister', help_text='Which pack size section this item belongs to', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within pack type group')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_materials', to='products.product')),
            ],
            options={
                'ordering': ['pack_type', 'order', 'item_code'],
            },
        ),
    ]
