# Generated by Django 4.2.7 on 2026-03-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_packaging_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mixing_appearance',
            field=models.CharField(blank=True, default='White Smooth Cream', help_text='Expected appearance of cream after mixing', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='mixing_clearance_end_items',
            field=models.JSONField(blank=True, default=list, help_text='List of strings for Mixing Line Clearance Ending Activities'),
        ),
        migrations.AddField(
            model_name='product',
            name='mixing_clearance_start_items',
            field=models.JSONField(blank=True, default=list, help_text='List of strings for Mixing Line Clearance Beginning Activities'),
        ),
        migrations.AddField(
            model_name='product',
            name='mixing_cool_temperature',
            field=models.DecimalField(blank=True, decimal_places=1, default=40.0, help_text='Cool-down temperature before QA sample in °C (e.g. 40.0)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mixing_equipment',
            field=models.JSONField(blank=True, default=list, help_text="List of dicts [{'name': 'Planetary Mixer', 'id': 'ON-01'}] for mixing equipment"),
        ),
        migrations.AddField(
            model_name='product',
            name='mixing_jacket_temperature',
            field=models.DecimalField(blank=True, decimal_places=1, default=70.0, help_text='Jacket temperature for mixing in °C (e.g. 70.0)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mixing_steps',
            field=models.JSONField(blank=True, default=list, help_text="List of dicts for mixing process steps e.g. [{'step': 1, 'instruction': '...'}]"),
        ),
        migrations.AddField(
            model_name='product',
            name='packing_instructions',
            field=models.JSONField(blank=True, default=list, help_text='List of strings for packing process instructions'),
        ),
        migrations.AddField(
            model_name='product',
            name='packing_reference_docs',
            field=models.JSONField(blank=True, default=list, help_text='List of reference document names for packing'),
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_packaging_clearance_end_items',
            field=models.JSONField(blank=True, default=list, help_text='List of strings for Secondary Packaging Line Clearance Ending Activities'),
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_packaging_clearance_start_items',
            field=models.JSONField(blank=True, default=list, help_text='List of strings for Secondary Packaging Line Clearance Beginning Activities'),
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_packing_steps',
            field=models.JSONField(blank=True, default=list, help_text='List of strings for secondary packing procedure steps'),
        ),
        migrations.AddField(
            model_name='product',
            name='tube_filling_clearance_end_items',
            field=models.JSONField(blank=True, default=list, help_text='List of strings for Tube Filling Line Clearance Ending Activities'),
        ),
        migrations.AddField(
            model_name='product',
            name='tube_filling_clearance_start_items',
            field=models.JSONField(blank=True, default=list, help_text='List of strings for Tube Filling Line Clearance Beginning Activities'),
        ),
        migrations.AddField(
            model_name='product',
            name='tube_filling_equipment',
            field=models.JSONField(blank=True, default=list, help_text="List of dicts [{'name': 'Tube Filling Machine', 'id': 'ON-03'}]"),
        ),
        migrations.AddField(
            model_name='product',
            name='tube_filling_hopper_temperature',
            field=models.DecimalField(blank=True, decimal_places=1, default=40.0, help_text='Hopper temperature during tube filling in °C (e.g. 40.0)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tube_filling_ipc_page_count',
            field=models.PositiveIntegerField(default=3, help_text='Number of production IPC report pages for tube filling'),
        ),
        migrations.AddField(
            model_name='product',
            name='tube_filling_qa_ipc_page_count',
            field=models.PositiveIntegerField(default=2, help_text='Number of QA IPC report pages for tube filling'),
        ),
        migrations.AddField(
            model_name='product',
            name='tube_filling_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=15.0, help_text='Net content per tube in grams (e.g. 15.00)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tube_filling_yield_max',
            field=models.DecimalField(blank=True, decimal_places=2, default=101.0, help_text='Maximum permissible yield % for tube filling (e.g. 101.00)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tube_filling_yield_min',
            field=models.DecimalField(blank=True, decimal_places=2, default=99.0, help_text='Minimum permissible yield % for tube filling (e.g. 99.00)', max_digits=5, null=True),
        ),
    ]
