# Generated by Django 4.2.7 on 2026-03-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_product_mixing_appearance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productingredient',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='productingredient',
            name='item_code',
            field=models.CharField(blank=True, help_text='Material code e.g. MCZ1NN (shown under description)', max_length=50),
        ),
        migrations.AddField(
            model_name='productingredient',
            name='lot_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of lots this ingredient is dispensed in (e.g. 1 or 4)'),
        ),
        migrations.AddField(
            model_name='productingredient',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (1=first row)'),
        ),
        migrations.AddField(
            model_name='productingredient',
            name='overage',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Overage in mg/g (usually 0)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productingredient',
            name='ingredient_name',
            field=models.CharField(help_text="Full description e.g. 'Miconazole Nitrate BP'", max_length=200),
        ),
        migrations.AlterField(
            model_name='productingredient',
            name='quantity_per_unit',
            field=models.DecimalField(decimal_places=4, help_text='Unit quantity in mg/g', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productingredient',
            name='unit_of_measure',
            field=models.CharField(default='mg/g', help_text='Unit e.g. mg/g, g, ml', max_length=20),
        ),
    ]
