# Generated by Django 5.2.8 on 2026-03-25 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_productingredient_item_code_overage_lot_count_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRevisionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_no', models.CharField(help_text='Revision number, e.g. 01, 02, 03', max_length=10)),
                ('changes_incorporated', models.TextField(help_text='Full text of changes incorporated in this revision')),
                ('reason_of_change', models.TextField(blank=True, help_text='Reason / justification for the change')),
                ('effective_date', models.CharField(blank=True, help_text='Effective date (leave blank if not yet assigned)', max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (lower = earlier; use 1, 2, 3 …)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_history', to='products.product')),
            ],
            options={
                'verbose_name': 'BMR Revision History',
                'verbose_name_plural': 'BMR Revision History',
                'ordering': ['order', 'revision_no'],
            },
        ),
    ]
