# Generated by Django 4.2.7 on 2026-03-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_productrevisionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='capsule_appearance',
            field=models.CharField(blank=True, help_text="Capsule appearance spec for IPQC table (e.g., Maroon cap printed 'KPI logo', Peach body printed 'KAM AMOXY 250')", max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='capsule_body_colour_trade',
            field=models.CharField(blank=True, help_text='Capsule body colour/print for Trade (e.g., Peach / KAM AMOXY 250)', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='capsule_body_colour_ug',
            field=models.CharField(blank=True, help_text='Capsule body colour/print for UG market (e.g., Peach / KAM AMOXY 250)', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='capsule_cap_colour_trade',
            field=models.CharField(blank=True, help_text='Capsule cap colour/print for Trade (e.g., Maroon / KPI)', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='capsule_cap_colour_ug',
            field=models.CharField(blank=True, help_text='Capsule cap colour/print for UG market (e.g., Maroon / UG & KPI LOGO)', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='capsule_machine_speed_max',
            field=models.DecimalField(blank=True, decimal_places=1, default=40.0, help_text='Maximum capsule filling machine speed in RPM (e.g., 40)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='capsule_machine_speed_min',
            field=models.DecimalField(blank=True, decimal_places=1, default=15.0, help_text='Minimum capsule filling machine speed in RPM (e.g., 15)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='capsule_size',
            field=models.CharField(blank=True, default='#1', help_text='Capsule shell size (e.g., #1)', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='fill_weight_mg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Standard fill weight per capsule in mg (e.g., 320.00)', max_digits=8, null=True),
        ),
    ]
