# Generated by Django 4.2.7 on 2026-03-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_capsule_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lock_length_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Capsule lock length maximum in mm (e.g., 19.90)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='lock_length_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Capsule lock length minimum in mm (e.g., 18.90)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='theoretical_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Theoretical batch weight in kg (e.g., 160.000)', max_digits=10, null=True),
        ),
    ]
