# Generated by Django 4.2.7 on 2026-03-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_add_capsule_lock_length_theoretical_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_weight_coated',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Average weight of coated tablets in mg (e.g., 556.81mg for FORMIN)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='blending_without_mag_time',
            field=models.CharField(blank=True, help_text='Blend time without Magnesium Stearate e.g. 15 minutes (coated tablets)', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='coating_clearance_end_items',
            field=models.JSONField(blank=True, default=list, help_text='List of strings for Film Coating Line Clearance Ending Activities'),
        ),
        migrations.AddField(
            model_name='product',
            name='coating_clearance_start_items',
            field=models.JSONField(blank=True, default=list, help_text='List of strings for Film Coating Line Clearance Beginning Activities'),
        ),
        migrations.AddField(
            model_name='product',
            name='coating_disintegration_max',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Post-coating maximum disintegration time in minutes (e.g., 30)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='coating_hardness_min',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Post-coating minimum hardness kg/cm² (e.g., 4 for NLT 4 kg/cm²)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='coating_hot_air_temp',
            field=models.CharField(blank=True, help_text='Coating hot air temperature e.g. 80 ± 5°C', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='coating_lot_count',
            field=models.PositiveIntegerField(default=4, help_text='Number of coating lots (e.g., 4 for FORMIN)'),
        ),
        migrations.AddField(
            model_name='product',
            name='coating_pan_speed',
            field=models.CharField(blank=True, help_text='Coating pan speed e.g. 10-14 RPM', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='coating_solution_instructions',
            field=models.JSONField(blank=True, default=list, help_text='List of strings for coating solution preparation steps'),
        ),
        migrations.AddField(
            model_name='product',
            name='coating_spray_pressure',
            field=models.CharField(blank=True, help_text='Coating spray gun pressure e.g. 2.0-2.25 kg/cm³', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='coating_storage_pressure',
            field=models.CharField(blank=True, help_text='Coating storage tank pressure e.g. 0.5-1.0 kg/cm³', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='coating_tablet_bed_temp',
            field=models.CharField(blank=True, help_text='Coating tablet bed temperature e.g. 40 ± 5°C', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='lubrication_with_mag_time',
            field=models.CharField(blank=True, help_text='Lubrication time with Magnesium Stearate e.g. 5 minutes (coated tablets)', max_length=50),
        ),
    ]
