# Generated by Django 4.2.7 on 2026-03-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_add_coating_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productingredient',
            name='ingredient_type',
            field=models.CharField(choices=[('active', 'Active Ingredient'), ('inactive', 'Inactive Ingredient'), ('excipient', 'Excipient'), ('coating', 'Coating Material')], max_length=20),
        ),
    ]
