# Generated by Django 5.2.8 on 2026-04-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_add_coating_ingredient_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='coating_equipment_params',
            field=models.JSONField(blank=True, default=list, help_text='List of dicts for equipment settings table rows: [{"name": "Spray gun pressure", "set_value": "2.0–2.25 kg/cm³"}, ...]'),
        ),
        migrations.AddField(
            model_name='product',
            name='coating_precautions',
            field=models.JSONField(blank=True, default=list, help_text='List of precaution strings shown on the coating page, e.g. ["Once started the film coating process should not be interrupted.", ...]'),
        ),
        migrations.AddField(
            model_name='product',
            name='coating_procedure_steps',
            field=models.JSONField(blank=True, default=list, help_text='List of procedure step strings for the coating procedure section, e.g. ["Load the tablets into the pan...", ...]'),
        ),
    ]
