# Generated by Django 4.2.7 on 2026-04-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_product_coating_equipment_params_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avg_empty_shell_weight_mg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average weight of empty capsule shells in mg (e.g., 91.00)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='capsule_body_print_trade',
            field=models.CharField(blank=True, help_text='Capsule body printing for Trade (e.g., KAM AMOXY 250)', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='capsule_body_print_ug',
            field=models.CharField(blank=True, help_text='Capsule body printing for UG market (e.g., KAM AMOXY 250)', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='capsule_cap_print_trade',
            field=models.CharField(blank=True, help_text='Capsule cap printing for Trade (e.g., KPI)', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='capsule_cap_print_ug',
            field=models.CharField(blank=True, help_text='Capsule cap printing for UG market (e.g., UG & KPI LOGO)', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='capsule_body_colour_trade',
            field=models.CharField(blank=True, help_text='Capsule body colour for Trade (e.g., Peach)', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='capsule_body_colour_ug',
            field=models.CharField(blank=True, help_text='Capsule body colour for UG market (e.g., Peach)', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='capsule_cap_colour_trade',
            field=models.CharField(blank=True, help_text='Capsule cap colour for Trade (e.g., Maroon)', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='capsule_cap_colour_ug',
            field=models.CharField(blank=True, help_text='Capsule cap colour for UG market (e.g., Maroon)', max_length=150),
        ),
    ]
