# Generated by Django 5.2.8 on 2026-05-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_capsule_print_shell_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='capsule_type',
            field=models.CharField(blank=True, choices=[('normal', 'Normal Capsule (Blister Packing)'), ('ug', 'Capsule UG (Bulk Packing)')], default='normal', help_text='Only applicable for capsules - normal (blister packing) or UG (bulk packing)', max_length=20),
        ),
    ]
